# Generated by Django 5.2.7 on 2025-11-05 04:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aseguradoras',
            fields=[
                ('aseguradora_id', models.CharField(help_text='ID único de la aseguradora (máximo 15 caracteres alfanuméricos).', max_length=15, primary_key=True, serialize=False)),
                ('aseguradora_nombre', models.CharField(help_text='Nombre de la aseguradora (máximo 30 caracteres).', max_length=30)),
                ('aseguradora_estado', models.CharField(choices=[('HABILITADO', 'HABILITADO'), ('DESHABILITADO', 'DESHABILITADO')], default='HABILITADO', help_text='Estado de la aseguradora: HABILITADO o DESHABILITADO.', max_length=13)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro (automática, no editable).')),
            ],
            options={
                'verbose_name': 'Aseguradora',
                'verbose_name_plural': 'Aseguradoras',
                'ordering': ['aseguradora_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Asesores',
            fields=[
                ('asesor_Id', models.CharField(help_text='Número de identificación del asesor (máximo 15 caracteres alfanuméricos).', max_length=15, primary_key=True, serialize=False)),
                ('asesor_nombre', models.CharField(help_text='Nombre completo del asesor (máximo 30 caracteres).', max_length=30)),
                ('asesor_estado', models.CharField(choices=[('HABILITADO', 'HABILITADO'), ('DESHABILITADO', 'DESHABILITADO')], default='HABILITADO', help_text='Estado del asesor: HABILITADO o DESHABILITADO.', max_length=13)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro (automática, no editable).')),
            ],
            options={
                'verbose_name': 'Asesor',
                'verbose_name_plural': 'Asesores',
                'ordering': ['asesor_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('departamento_id', models.PositiveSmallIntegerField(help_text='Código numérico del departamento (2 dígitos: 0–99).', primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('departamento_nombre', models.CharField(help_text='Nombre del departamento (máximo 60 caracteres).', max_length=60)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['departamento_id'],
            },
        ),
        migrations.CreateModel(
            name='Tasas',
            fields=[
                ('tipo_tasa', models.CharField(choices=[('CON SEGURO', 'CON SEGURO'), ('SIN SEGURO', 'SIN SEGURO')], help_text="Tipo de tasa: 'CON SEGURO' o 'SIN SEGURO'.", max_length=10, primary_key=True, serialize=False)),
                ('tasa', models.DecimalField(decimal_places=2, help_text='Valor de la tasa (por ejemplo: 12.50). Dos enteros y dos decimales.', max_digits=4)),
            ],
            options={
                'verbose_name': 'Tasa',
                'verbose_name_plural': 'Tasas',
            },
        ),
        migrations.CreateModel(
            name='Tipos_Identificacion',
            fields=[
                ('tipo_id', models.CharField(help_text='Código del tipo de identificación (máximo 3 caracteres).', max_length=3, primary_key=True, serialize=False)),
                ('descripcion_id', models.CharField(help_text='Descripción del tipo de identificación (máximo 20 caracteres).', max_length=20)),
            ],
            options={
                'verbose_name': 'Tipo de Identificación',
                'verbose_name_plural': 'Tipos de Identificación',
                'ordering': ['tipo_id'],
            },
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio_id', models.PositiveSmallIntegerField(help_text='Código numérico del municipio (3 dígitos: 0–999).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)])),
                ('municipio_nombre', models.CharField(help_text='Nombre del municipio (máximo 60 caracteres).', max_length=60)),
                ('departamento', models.ForeignKey(help_text='Departamento al que pertenece el municipio.', on_delete=django.db.models.deletion.PROTECT, to='appfinancia.departamentos')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'ordering': ['departamento', 'municipio_id'],
                'unique_together': {('municipio_id', 'departamento')},
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('cliente_id', models.BigIntegerField(help_text='Número de identificación único del cliente (hasta 15 dígitos).', primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre del cliente (máximo 40 caracteres).', max_length=40)),
                ('apellido', models.CharField(help_text='Apellido del cliente (máximo 40 caracteres).', max_length=40)),
                ('fecha_nacimiento', models.DateField(help_text='Fecha de nacimiento (formato: AAAA-MM-DD). Debe estar entre 1900-01-01 y hoy.')),
                ('telefono', models.BigIntegerField(help_text='Número de teléfono (10 dígitos, sin espacios ni guiones).')),
                ('direccion', models.CharField(help_text='Dirección del cliente (máximo 80 caracteres).', max_length=80)),
                ('email', models.EmailField(help_text='Correo electrónico del cliente (máximo 50 caracteres).', max_length=50, validators=[django.core.validators.EmailValidator()])),
                ('estado', models.CharField(choices=[('HABILITADO', 'HABILITADO'), ('DESHABILITADO', 'DESHABILITADO')], default='HABILITADO', help_text='Estado del cliente: HABILITADO o DESHABILITADO.', max_length=13)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro (automática, no editable).')),
                ('departamento', models.ForeignKey(help_text='Departamento del cliente.', on_delete=django.db.models.deletion.PROTECT, to='appfinancia.departamentos')),
                ('municipio', models.ForeignKey(help_text='Municipio del cliente. Debe pertenecer al departamento seleccionado.', on_delete=django.db.models.deletion.PROTECT, to='appfinancia.municipios')),
                ('tipo_id', models.ForeignKey(help_text='Tipo de identificación (ej. CC, TI, CE, PA).', on_delete=django.db.models.deletion.PROTECT, to='appfinancia.tipos_identificacion')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
