# Generated by Django 5.2.7 on 2025-11-06 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numeradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerador_prestamo', models.PositiveIntegerField(default=1000)),
                ('numerador_transaccion', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Numerador',
                'verbose_name_plural': 'Numeradores',
            },
        ),
        migrations.CreateModel(
            name='Vendedores',
            fields=[
                ('cod_venta_id', models.CharField(help_text='Código único del vendedor (máximo 15 caracteres alfanuméricos).', max_length=15, primary_key=True, serialize=False)),
                ('cod_venta_nombre', models.CharField(help_text='Nombre del vendedor (máximo 30 caracteres).', max_length=30)),
                ('estado', models.CharField(choices=[('HABILITADO', 'HABILITADO'), ('DESHABILITADO', 'DESHABILITADO')], default='HABILITADO', help_text='Estado del vendedor: HABILITADO o DESHABILITADO.', max_length=13)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro (automática, no editable).')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'ordering': ['cod_venta_nombre'],
            },
        ),
    ]
