# Generated by Django 5.2.7 on 2025-11-06 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0002_numeradores_vendedores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desembolsos',
            fields=[
                ('prestamo_id', models.BigIntegerField(editable=False, help_text='ID único del préstamo, generado automáticamente.', primary_key=True, serialize=False)),
                ('tasa', models.DecimalField(decimal_places=2, help_text='Tasa de interés (dos enteros y dos decimales).', max_digits=4)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor total del préstamo (mayor que 0).', max_digits=15)),
                ('valor_cuota_inicial', models.DecimalField(decimal_places=2, help_text='Valor de la cuota inicial (mayor que 0).', max_digits=15)),
                ('valor_cuota_mensual', models.DecimalField(decimal_places=2, help_text='Valor de la cuota mensual (mayor que 0).', max_digits=15)),
                ('valor_seguro_mes', models.DecimalField(decimal_places=2, default=0, help_text='Valor del seguro mensual (puede ser 0).', max_digits=15)),
                ('tiene_fee', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], help_text="Indica si el préstamo tiene fee ('SI' o 'NO').", max_length=2)),
                ('plazo_en_meses', models.PositiveSmallIntegerField(help_text='Plazo en meses (1 a 24).')),
                ('fecha_desembolso', models.DateField(help_text='Fecha de desembolso (hoy o hasta 10 días atrás, no futura).')),
                ('fecha_vencimiento', models.DateField(editable=False, help_text='Fecha de vencimiento calculada automáticamente.')),
                ('fecha_suspension_intereses', models.DateField(blank=True, help_text='Fecha en la que se suspenden los intereses (opcional).', null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('DESEMBOLSADO', 'DESEMBOLSADO'), ('ANULADO', 'ANULADO')], default='PENDIENTE', help_text='Estado del desembolso.', max_length=13)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro (automática, no editable).')),
                ('aseguradora', models.ForeignKey(help_text='Aseguradora del préstamo.', on_delete=django.db.models.deletion.PROTECT, to='appfinancia.aseguradoras')),
                ('asesor', models.ForeignKey(help_text='Asesor responsable.', on_delete=django.db.models.deletion.PROTECT, to='appfinancia.asesores')),
                ('cliente', models.ForeignKey(help_text='Cliente asociado al desembolso.', on_delete=django.db.models.deletion.PROTECT, to='appfinancia.clientes')),
                ('tipo_tasa', models.ForeignKey(help_text="Tipo de tasa aplicada (ej. 'CON SEGURO', 'SIN SEGURO').", on_delete=django.db.models.deletion.PROTECT, to='appfinancia.tasas')),
                ('vendedor', models.ForeignKey(help_text='Vendedor asociado.', on_delete=django.db.models.deletion.PROTECT, to='appfinancia.vendedores')),
            ],
            options={
                'verbose_name': 'Desembolso',
                'verbose_name_plural': 'Desembolsos',
                'ordering': ['-fecha_desembolso'],
            },
        ),
    ]
