# Generated by Django 5.2.7 on 2025-11-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0003_desembolsos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conceptos_Transacciones',
            fields=[
                ('concepto_id', models.CharField(help_text='Identificador único del concepto (máximo 10 caracteres).', max_length=10, primary_key=True, serialize=False)),
                ('codigo_transaccion', models.CharField(help_text='Código de transacción único (máximo 10 caracteres, no duplicable).', max_length=10, unique=True)),
                ('descripcion', models.CharField(help_text='Descripción del concepto de transacción (máximo 60 caracteres).', max_length=60)),
                ('estado', models.CharField(choices=[('HABILITADO', 'HABILITADO'), ('DESHABILITADO', 'DESHABILITADO')], default='HABILITADO', help_text='Estado del concepto: HABILITADO o DESHABILITADO.', max_length=13)),
            ],
            options={
                'verbose_name': 'Concepto de Transacción',
                'verbose_name_plural': 'Conceptos de Transacciones (Códigos de Transacciones)',
                'ordering': ['concepto_id'],
            },
        ),
    ]
