# Generated by Django 5.2.7 on 2025-11-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0004_conceptos_transacciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacion_id', models.CharField(help_text='Código de operación (máximo 20 caracteres).', max_length=20)),
                ('evento_id', models.CharField(help_text='Código de evento (máximo 20 caracteres).', max_length=20)),
                ('comentario', models.CharField(help_text='Texto del comentario (máximo 60 caracteres).', max_length=60)),
                ('estado', models.CharField(choices=[('HABILITADO', 'HABILITADO'), ('DESHABILITADO', 'DESHABILITADO')], default='HABILITADO', help_text='Estado del comentario: HABILITADO o DESHABILITADO.', max_length=13)),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios (Catálogo de Comentarios para Negocios/Préstamos)',
                'ordering': ['operacion_id', 'evento_id'],
                'unique_together': {('operacion_id', 'evento_id')},
            },
        ),
    ]
