# Generated by Django 5.2.7 on 2025-11-07 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0005_comentarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Politicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad_min', models.PositiveSmallIntegerField(default=1, help_text='Edad mínima permitida para otorgar crédito.')),
                ('edad_max', models.PositiveSmallIntegerField(default=1, help_text='Edad máxima permitida para otorgar crédito.')),
                ('valor_cred_min', models.DecimalField(decimal_places=2, default=1.0, help_text='Valor mínimo del crédito (13 enteros + 2 decimales).', max_digits=15)),
                ('valor_cred_max', models.DecimalField(decimal_places=2, default=1.0, help_text='Valor máximo del crédito.', max_digits=15)),
                ('porcentaje_min_cuota_ini', models.DecimalField(decimal_places=2, default=1.0, help_text='Porcentaje mínimo de cuota inicial (2 enteros + 2 decimales).', max_digits=4)),
                ('porcentaje_max_cuota_ini', models.DecimalField(decimal_places=2, default=1.0, help_text='Porcentaje máximo de cuota inicial.', max_digits=4)),
                ('tasa_min', models.DecimalField(decimal_places=2, default=1.0, help_text='Tasa mínima permitida (2 enteros + 2 decimales).', max_digits=4)),
                ('tasa_max', models.DecimalField(decimal_places=2, default=1.0, help_text='Tasa máxima permitida.', max_digits=4)),
                ('plazo_min', models.PositiveSmallIntegerField(default=1, help_text='Plazo mínimo en meses (hasta 3 dígitos).')),
                ('plazo_max', models.PositiveSmallIntegerField(default=1, help_text='Plazo máximo en meses.')),
            ],
            options={
                'verbose_name': 'Política',
                'verbose_name_plural': 'Políticas (Única Fila Global)',
            },
        ),
    ]
