# Generated by Django 5.2.7 on 2025-11-07 06:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0006_politicas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='politicas',
            options={'verbose_name': 'Política Global', 'verbose_name_plural': 'Políticas Globales'},
        ),
        migrations.AlterField(
            model_name='politicas',
            name='edad_max',
            field=models.PositiveSmallIntegerField(default=75, help_text='Edad máxima permitida (ej. 75)'),
        ),
        migrations.AlterField(
            model_name='politicas',
            name='edad_min',
            field=models.PositiveSmallIntegerField(default=18, help_text='Edad mínima permitida (ej. 18)'),
        ),
        migrations.AlterField(
            model_name='politicas',
            name='plazo_max',
            field=models.PositiveSmallIntegerField(default=60, help_text='Plazo máximo en meses'),
        ),
        migrations.AlterField(
            model_name='politicas',
            name='plazo_min',
            field=models.PositiveSmallIntegerField(default=12, help_text='Plazo mínimo en meses'),
        ),
        migrations.AlterField(
            model_name='politicas',
            name='porcentaje_max_cuota_ini',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Porcentaje máximo de cuota inicial (%)', max_digits=4),
        ),
        migrations.AlterField(
            model_name='politicas',
            name='porcentaje_min_cuota_ini',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Porcentaje mínimo de cuota inicial (%)', max_digits=4),
        ),
        migrations.AlterField(
            model_name='politicas',
            name='tasa_max',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.50'), help_text='Tasa de interés máxima mensual (%)', max_digits=4),
        ),
        migrations.AlterField(
            model_name='politicas',
            name='tasa_min',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='Tasa de interés mínima mensual (%)', max_digits=4),
        ),
        migrations.AlterField(
            model_name='politicas',
            name='valor_cred_max',
            field=models.DecimalField(decimal_places=2, default=Decimal('50000000.00'), help_text='Valor máximo del crédito (ej. 50.000.000,00)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='politicas',
            name='valor_cred_min',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000000.00'), help_text='Valor mínimo del crédito (ej. 1.000.000,00)', max_digits=15),
        ),
    ]
