# Generated by Django 5.2.7 on 2025-11-10 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0007_alter_politicas_options_alter_politicas_edad_max_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Numeradores',
        ),
    ]
