# Generated by Django 5.2.7 on 2025-11-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0008_delete_numeradores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numeradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerador_asientos', models.PositiveIntegerField(default=1, help_text='Contador para asientos contables.')),
                ('numerador_transaccion', models.PositiveIntegerField(default=1, help_text='Contador para transacciones.')),
                ('numerador_prestamo', models.PositiveIntegerField(default=1, help_text='Contador para préstamos.')),
                ('numerador_conciliacion', models.PositiveIntegerField(default=1, help_text='Contador para conciliaciones.')),
                ('numerador_pagos', models.PositiveIntegerField(default=1, help_text='Contador para pagos.')),
                ('numerador_aux_1', models.PositiveIntegerField(default=1, help_text='Contador auxiliar 1.')),
                ('numerador_aux_2', models.PositiveIntegerField(default=1, help_text='Contador auxiliar 2.')),
                ('numerador_aux_3', models.PositiveIntegerField(default=1, help_text='Contador auxiliar 3.')),
                ('numerador_aux_4', models.PositiveIntegerField(default=1, help_text='Contador auxiliar 4.')),
                ('numerador_aux_5', models.PositiveIntegerField(default=1, help_text='Contador auxiliar 5.')),
            ],
            options={
                'verbose_name': 'Numerador',
                'verbose_name_plural': 'Numeradores (Única Fila Global)',
            },
        ),
        migrations.AddField(
            model_name='politicas',
            name='dias_max_desembolso_atras',
            field=models.PositiveSmallIntegerField(default=10, help_text='Máximo de días permitidos hacia atras'),
        ),
        migrations.DeleteModel(
            name='Desembolsos',
        ),
    ]
