# Generated by Django 5.2.7 on 2025-11-10 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0009_numeradores_politicas_dias_max_desembolso_atras_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desembolsos',
            fields=[
                ('prestamo_id', models.BigIntegerField(editable=False, help_text='ID único del préstamo, generado automáticamente.', primary_key=True, serialize=False)),
                ('tasa', models.DecimalField(decimal_places=2, help_text='Tasa de interés aplicada (dos enteros, dos decimales).', max_digits=4)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor total del préstamo.', max_digits=15)),
                ('valor_cuota_1', models.DecimalField(decimal_places=2, help_text='Valor de la primera cuota.', max_digits=15)),
                ('numero_transaccion_cuota_1', models.CharField(blank=True, help_text='Número de transacción de la primera cuota (opcional).', max_length=10)),
                ('valor_cuota_mensual', models.DecimalField(decimal_places=2, help_text='Valor de la cuota mensual.', max_digits=15)),
                ('valor_seguro_mes', models.DecimalField(decimal_places=2, default=0, help_text='Valor del seguro mensual.', max_digits=15)),
                ('tiene_fee', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], help_text="Indica si el préstamo tiene fee ('SI' o 'NO').", max_length=2)),
                ('dia_cobro', models.PositiveSmallIntegerField(help_text='Día de cobro mensual (1 a 30).')),
                ('plazo_en_meses', models.PositiveSmallIntegerField(help_text='Plazo en meses.')),
                ('fecha_desembolso', models.DateField(help_text='Fecha de desembolso.')),
                ('fecha_vencimiento', models.DateField(editable=False, help_text='Fecha de vencimiento calculada automáticamente.')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('DESEMBOLSADO', 'DESEMBOLSADO'), ('ANULADO', 'ANULADO')], default='PENDIENTE', help_text='Estado del desembolso.', max_length=13)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación (automática).')),
                ('aseguradora', models.ForeignKey(help_text='Aseguradora del préstamo.', on_delete=django.db.models.deletion.PROTECT, to='appfinancia.aseguradoras')),
                ('asesor', models.ForeignKey(help_text='Asesor responsable.', on_delete=django.db.models.deletion.PROTECT, to='appfinancia.asesores')),
                ('cliente', models.ForeignKey(help_text='Cliente asociado.', on_delete=django.db.models.deletion.PROTECT, to='appfinancia.clientes')),
                ('tipo_tasa', models.ForeignKey(help_text="Tipo de tasa (ej. 'CON SEGURO').", on_delete=django.db.models.deletion.PROTECT, to='appfinancia.tasas')),
                ('vendedor', models.ForeignKey(help_text='Vendedor asociado.', on_delete=django.db.models.deletion.PROTECT, to='appfinancia.vendedores')),
            ],
            options={
                'verbose_name': 'Desembolso',
                'verbose_name_plural': 'Desembolsos',
                'ordering': ['-fecha_desembolso'],
            },
        ),
    ]
