# Generated by Django 5.2.7 on 2025-11-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0010_desembolsos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desembolsos',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('DESEMBOLSADO', 'DESEMBOLSADO'), ('ANULADO', 'ANULADO')], default='PENDIENTE', editable=False, help_text='Estado del desembolso.', max_length=13),
        ),
    ]
