# Generated by Django 5.2.7 on 2025-11-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0011_alter_desembolsos_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desembolsos',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('DESEMBOLSADO', 'DESEMBOLSADO'), ('ANULADO', 'ANULADO')], default='PENDIENTE', help_text='Estado del desembolso.', max_length=13),
        ),
    ]
