# Generated by Django 5.2.7 on 2025-11-11 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0012_alter_desembolsos_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desembolsos',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor total del préstamo.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='valor_cuota_1',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor de la primera cuota.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='valor_cuota_mensual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor de la cuota mensual.', max_digits=15),
        ),
    ]
