# Generated by Django 5.2.7 on 2025-11-11 00:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0013_alter_desembolsos_valor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desembolsos',
            name='fecha_desembolso',
            field=models.DateField(default=datetime.date(2025, 11, 10), help_text='Fecha de desembolso.'),
        ),
    ]
