# Generated by Django 5.2.7 on 2025-11-11 02:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0014_alter_desembolsos_fecha_desembolso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desembolsos',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de creación (automática, no editable).'),
        ),
        migrations.AlterField(
            model_name='politicas',
            name='dias_max_desembolso_atras',
            field=models.PositiveSmallIntegerField(default=0, help_text='Dias máximo desembolsos con fecha anterior'),
        ),
    ]
