# Generated by Django 5.2.7 on 2025-11-11 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0015_alter_desembolsos_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desembolsos',
            name='plazo_en_meses',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Plazo en meses.'),
        ),
    ]
