# Generated by Django 5.2.7 on 2025-11-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0016_alter_desembolsos_plazo_en_meses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desembolsos',
            name='plazo_en_meses',
            field=models.PositiveSmallIntegerField(default=0, help_text='Plazo en meses.'),
        ),
    ]
