# Generated by Django 5.2.7 on 2025-11-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0017_alter_desembolsos_plazo_en_meses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desembolsos',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, editable=False, help_text='Fecha de vencimiento calculada automáticamente.', null=True),
        ),
    ]
