# Generated by Django 5.2.7 on 2025-11-11 05:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0018_alter_desembolsos_fecha_vencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desembolsos',
            name='fecha_desembolso',
            field=models.DateField(default=datetime.date(2025, 11, 11), help_text='Fecha de desembolso.'),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='numero_transaccion_cuota_1',
            field=models.CharField(blank=True, help_text='Número de transacción de la primera cuota (opcional).', max_length=10, verbose_name='#Trans.Cuota 1'),
        ),
    ]
