# Generated by Django 5.2.7 on 2025-11-12 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0019_alter_desembolsos_fecha_desembolso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desembolsos',
            name='tasa',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tasa de interés aplicada (dos enteros, dos decimales).', max_digits=4),
        ),
    ]
