# Generated by Django 5.2.7 on 2025-11-13 02:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0020_alter_desembolsos_tasa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desembolsos',
            name='dia_cobro',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Día de cobro mensual (1 a 30).'),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='fecha_desembolso',
            field=models.DateField(default=datetime.date(2025, 11, 12), help_text='Fecha de desembolso.'),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='plazo_en_meses',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Plazo en meses.'),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='tipo_tasa',
            field=models.ForeignKey(blank=True, help_text="Tipo de tasa (ej. 'CON SEGURO').", on_delete=django.db.models.deletion.PROTECT, to='appfinancia.tasas'),
        ),
    ]
