# Generated by Django 5.2.7 on 2025-11-14 01:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0021_alter_desembolsos_dia_cobro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('secuencial', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('fecha_proceso', models.DateField()),
                ('user_name', models.CharField(max_length=30)),
                ('evento_realizado', models.CharField(max_length=30)),
                ('proceso', models.CharField(max_length=10)),
                ('resultado', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Bitácora',
                'verbose_name_plural': 'Bitácoras',
            },
        ),
        migrations.RemoveField(
            model_name='numeradores',
            name='numerador_asientos',
        ),
        migrations.AddField(
            model_name='numeradores',
            name='numerador_operacion',
            field=models.PositiveIntegerField(default=1, help_text='Contador para operacion contables.'),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='fecha_desembolso',
            field=models.DateField(default=datetime.date(2025, 11, 13), help_text='Fecha de desembolso.'),
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('Id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField(auto_now_add=True, help_text='Fecha y hora movimiento')),
                ('valor_movimiento', models.DecimalField(decimal_places=2, help_text='Valor mvto', max_digits=16)),
                ('fecha_valor_mvto', models.DateField(help_text='Fecha valor')),
                ('Asesores', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appfinancia.asesores')),
                ('cliente_id', models.ForeignKey(help_text="Selecciona un cliente, Puedes añadir una nueva categoría haciendo clic en el signo '+'.", on_delete=django.db.models.deletion.CASCADE, to='appfinancia.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasa', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_cuota_1', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_cuota_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_seguro_mes', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tiene_fee', models.CharField(default='NO', max_length=2)),
                ('dia_cobro', models.PositiveSmallIntegerField(default=1)),
                ('plazo_en_meses', models.PositiveSmallIntegerField(default=0)),
                ('fecha_desembolso', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('suspender_causacion', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], help_text="Tiene suspendida la causacion intrs ('SI' o 'NO').", max_length=2)),
                ('fecha_suspension_causacion', models.DateField()),
                ('revocatoria', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], help_text="Tiene Revocatoria ('SI' o 'NO').", max_length=2)),
                ('fecha_revocatoria', models.DateField()),
                ('aseguradora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appfinancia.aseguradoras')),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appfinancia.asesores')),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appfinancia.clientes')),
                ('prestamo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appfinancia.desembolsos')),
                ('tipo_tasa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appfinancia.tasas')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appfinancia.vendedores')),
            ],
            options={
                'verbose_name': 'Prestamo',
                'verbose_name_plural': 'Prestamos',
            },
        ),
        migrations.CreateModel(
            name='Plan_Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuota_id', models.PositiveIntegerField()),
                ('fecha_valor_inicial', models.DateField()),
                ('fecha_de_vcto_cuota', models.DateField()),
                ('tipo_de_cuota', models.CharField(choices=[('C', 'Capital'), ('I', 'Intereses'), ('N', 'Normal (Capital + Interés)')], max_length=1)),
                ('monto_capital', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monto_interes', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monto_seguro', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monto_gastos', models.DecimalField(decimal_places=2, max_digits=15)),
                ('saldo_capital', models.DecimalField(decimal_places=2, max_digits=15)),
                ('saldo_interes', models.DecimalField(decimal_places=2, max_digits=15)),
                ('saldo_seguro', models.DecimalField(decimal_places=2, max_digits=15)),
                ('saldo_gastos', models.DecimalField(decimal_places=2, max_digits=15)),
                ('prestamo', models.ForeignKey(db_column='prestamo_id', on_delete=django.db.models.deletion.CASCADE, to='appfinancia.prestamos')),
            ],
            options={
                'verbose_name': 'Plan de Pago',
                'verbose_name_plural': 'Planes de Pago',
                'db_table': 'plan_pagos',
                'unique_together': {('prestamo', 'cuota_id')},
            },
        ),
        migrations.CreateModel(
            name='Historia_Prestamos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_efectiva', models.DateField()),
                ('fecha_proceso', models.DateField()),
                ('ordinal_interno', models.IntegerField()),
                ('numero_operacion', models.PositiveIntegerField(default=1, help_text='secuencial de operacion')),
                ('fecha_vencimiento', models.DateField()),
                ('tasa', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('monto_transaccion', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('saldo_capital', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('abono_capital', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('intrs_ctes', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('seguro', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ints_ctes', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('usuario', models.CharField(max_length=15)),
                ('concepto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appfinancia.conceptos_transacciones')),
                ('prestamo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appfinancia.prestamos')),
            ],
            options={
                'verbose_name': 'Historia Prestamo',
                'verbose_name_plural': 'Historia Prestamos',
                'unique_together': {('prestamo_id', 'fecha_efectiva', 'fecha_proceso', 'ordinal_interno', 'numero_operacion')},
            },
        ),
    ]
