# Generated by Django 5.2.7 on 2025-11-14 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0022_bitacora_remove_numeradores_numerador_asientos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desembolsos',
            name='fecha_desembolso',
            field=models.DateField(default=datetime.date(2025, 11, 14), help_text='Fecha de desembolso.'),
        ),
    ]
