# Generated by Django 5.2.7 on 2025-11-14 15:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0023_alter_desembolsos_fecha_desembolso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asesores',
            old_name='asesor_Id',
            new_name='asesor_id',
        ),
        migrations.RenameField(
            model_name='desembolsos',
            old_name='aseguradora',
            new_name='aseguradora_id',
        ),
        migrations.RenameField(
            model_name='desembolsos',
            old_name='asesor',
            new_name='asesor_id',
        ),
        migrations.RenameField(
            model_name='desembolsos',
            old_name='cliente',
            new_name='cliente_id',
        ),
        migrations.RenameField(
            model_name='desembolsos',
            old_name='vendedor',
            new_name='vendedor_id',
        ),
        migrations.RenameField(
            model_name='movimientos',
            old_name='Asesores',
            new_name='asesor_id',
        ),
        migrations.RenameField(
            model_name='movimientos',
            old_name='Id_movimiento',
            new_name='id_movimiento',
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='fecha_desembolso',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha de desembolso.'),
        ),
    ]
