# Generated by Django 5.2.7 on 2025-11-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0024_rename_asesor_id_asesores_asesor_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamos',
            old_name='aseguradora',
            new_name='aseguradora_id',
        ),
        migrations.RenameField(
            model_name='prestamos',
            old_name='asesor',
            new_name='asesor_id',
        ),
        migrations.RenameField(
            model_name='prestamos',
            old_name='vendedor',
            new_name='vendedor_id',
        ),
        migrations.AlterUniqueTogether(
            name='historia_prestamos',
            unique_together={('prestamo_id', 'fecha_efectiva', 'fecha_proceso', 'numero_operacion')},
        ),
        migrations.AddField(
            model_name='historia_prestamos',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('CANCELADO', 'Cancelado'), ('MOROSO', 'Moroso')], default='PENDIENTE', max_length=10),
        ),
        migrations.AddField(
            model_name='historia_prestamos',
            name='numero_cuota',
            field=models.IntegerField(blank=True, help_text='Número de cuota a la que pertenece', null=True),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='estado',
            field=models.CharField(choices=[('ELABORACION', 'ELABORACION'), ('PENDIENTE', 'PENDIENTE'), ('DESEMBOLSADO', 'DESEMBOLSADO'), ('ANULADO', 'ANULADO')], default='ELABORACION', help_text='Estado del desembolso.', max_length=13),
        ),
        migrations.DeleteModel(
            name='Plan_Pagos',
        ),
        migrations.RemoveField(
            model_name='historia_prestamos',
            name='ints_ctes',
        ),
        migrations.RemoveField(
            model_name='historia_prestamos',
            name='saldo_capital',
        ),
    ]
