# Generated by Django 5.2.7 on 2025-11-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0025_rename_aseguradora_prestamos_aseguradora_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamos',
            name='fecha_revocatoria',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='fecha_suspension_causacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
