# Generated by Django 5.2.7 on 2025-11-16 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0026_alter_prestamos_fecha_revocatoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='evento_realizado',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='proceso',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='resultado',
            field=models.TextField(),
        ),
    ]
