# Generated by Django 5.2.7 on 2025-11-16 05:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0028_alter_municipios_municipio_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipios',
            name='municipio_id',
            field=models.PositiveIntegerField(help_text='Código numérico del municipio (5 dígitos: 0–99999).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)]),
        ),
    ]
