# Generated by Django 5.2.7 on 2025-11-17 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0029_alter_municipios_municipio_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentarios',
        ),
    ]
