# Generated by Django 5.2.7 on 2025-11-17 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0030_delete_comentarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('comentario_id', models.AutoField(help_text='ID único autonumerado del comentario.', primary_key=True, serialize=False)),
                ('operacion_id', models.CharField(help_text='Código de operación (máximo 20 caracteres).', max_length=20)),
                ('evento_id', models.CharField(help_text='Código de evento (máximo 20 caracteres).', max_length=20)),
                ('comentario', models.CharField(help_text='Texto del comentario (máximo 60 caracteres).', max_length=60)),
                ('estado', models.CharField(choices=[('HABILITADO', 'HABILITADO'), ('DESHABILITADO', 'DESHABILITADO')], default='HABILITADO', help_text='Estado del comentario.', max_length=13)),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'unique_together': {('operacion_id', 'evento_id')},
            },
        ),
    ]
