# Generated by Django 5.2.7 on 2025-11-17 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0031_comentarios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conceptos_transacciones',
            options={'ordering': ['concepto_id'], 'verbose_name': 'Concepto de Transacción', 'verbose_name_plural': 'Conceptos de Transacciones'},
        ),
        migrations.AlterModelOptions(
            name='numeradores',
            options={'verbose_name': 'Numerador', 'verbose_name_plural': 'Numeradores)'},
        ),
    ]
