# Generated by Django 5.2.7 on 2025-11-17 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0032_alter_conceptos_transacciones_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='numeradores',
            options={'verbose_name': 'Numerador', 'verbose_name_plural': 'Numeradores'},
        ),
    ]
