# Generated by Django 5.2.7 on 2025-11-17 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0033_alter_numeradores_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comentarios',
            unique_together=set(),
        ),
    ]
