# Generated by Django 5.2.7 on 2025-11-17 16:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0034_alter_comentarios_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios_Prestamos',
            fields=[
                ('numero_comentario', models.AutoField(help_text='Número secuencial único del comentario (generado automáticamente).', primary_key=True, serialize=False)),
                ('fecha_comentario', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora del comentario (automática al crear).')),
                ('comentario', models.CharField(blank=True, help_text='Texto personalizado del comentario (máximo 60 caracteres).', max_length=60)),
                ('comentario_catalogo', models.ForeignKey(help_text='Comentario estandarizado del catálogo.', on_delete=django.db.models.deletion.PROTECT, to='appfinancia.comentarios')),
                ('creado_por', models.ForeignKey(editable=False, help_text='Usuario que registró el comentario.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('prestamo', models.ForeignKey(db_column='prestamo_id', help_text='Préstamo asociado (admite múltiples comentarios).', on_delete=django.db.models.deletion.CASCADE, to='appfinancia.desembolsos')),
            ],
            options={
                'verbose_name': 'Comentario de Préstamo',
                'verbose_name_plural': 'Comentarios de Préstamos',
                'ordering': ['-fecha_comentario'],
            },
        ),
    ]
