# Generated by Django 5.2.7 on 2025-11-17 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0035_comentarios_prestamos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios_prestamos',
            name='comentario',
        ),
    ]
