# Generated by Django 5.2.7 on 2025-11-19 03:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0036_remove_comentarios_prestamos_comentario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentarios_prestamos',
            options={},
        ),
        migrations.AlterField(
            model_name='comentarios_prestamos',
            name='creado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que registró el comentario.', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='dia_cobro',
            field=models.PositiveSmallIntegerField(default=1, help_text='Día de cobro mensual (1 a 30).'),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='estado',
            field=models.CharField(choices=[('ELABORACION', 'Elaboración'), ('PENDIENTE', 'Pendiente'), ('DESEMBOLSADO', 'Desembolsado'), ('ANULADO', 'Anulado')], default='ELABORACION', help_text='Estados del desembolso:Elaboración-->Pendiente-->Desembolsar.', max_length=13),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Fecha y hora de creación (automática).'),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='plazo_en_meses',
            field=models.PositiveSmallIntegerField(default=12, help_text='Plazo en meses.'),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='tiene_fee',
            field=models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='NO', help_text="Indica si el préstamo tiene fee ('SI' o 'NO').", max_length=2),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='tipo_tasa',
            field=models.ForeignKey(default=None, help_text="Tipo de tasa (ej. 'CON SEGURO').", on_delete=django.db.models.deletion.PROTECT, to='appfinancia.tasas'),
        ),
    ]
