# Generated by Django 5.2.7 on 2025-11-19 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0037_alter_comentarios_prestamos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desembolsos',
            name='estado',
            field=models.CharField(choices=[('ELABORACION', 'Elaboración'), ('A DESEMBOLSAR', 'A desembolsar'), ('DESEMBOLSADO', 'Desembolsado'), ('ANULADO', 'Anulado')], default='ELABORACION', help_text='Estados del desembolso:Elaboración-->Pendiente-->Desembolsar.', max_length=14),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='tipo_tasa',
            field=models.ForeignKey(blank=True, help_text="Tipo de tasa (ej. 'CON SEGURO').", null=True, on_delete=django.db.models.deletion.PROTECT, to='appfinancia.tasas'),
        ),
        migrations.AlterField(
            model_name='historia_prestamos',
            name='estado',
            field=models.CharField(choices=[('A DESEMBOLSAR', 'A desembolsar'), ('PAGADO', 'Pagado'), ('CANCELADO', 'Cancelado'), ('MOROSO', 'Moroso')], default='PENDIENTE', max_length=14),
        ),
    ]
