# Generated by Django 5.2.7 on 2025-11-21 14:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0038_alter_desembolsos_estado_alter_desembolsos_tipo_tasa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desembolsos',
            name='aseguradora_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appfinancia.aseguradoras'),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='asesor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appfinancia.asesores'),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='cliente_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appfinancia.clientes'),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='dia_cobro',
            field=models.PositiveSmallIntegerField(default=1, help_text='Día de cobro (1-30)'),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='estado',
            field=models.CharField(choices=[('ELABORACION', 'Elaboración'), ('A_DESEMBOLSAR', 'A desembolsar'), ('DESEMBOLSADO', 'Desembolsado'), ('ANULADO', 'Anulado')], default='ELABORACION', max_length=14),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='fecha_desembolso',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='numero_transaccion_cuota_1',
            field=models.CharField(blank=True, max_length=10, verbose_name='#Trans.Cuota 1'),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='plazo_en_meses',
            field=models.PositiveSmallIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='tasa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='tiene_fee',
            field=models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='NO', max_length=2),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='valor_cuota_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='valor_cuota_mensual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='valor_seguro_mes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='vendedor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appfinancia.vendedores'),
        ),
    ]
