# Generated by Django 5.2.7 on 2025-11-24 22:30
# appfinancia/migrations/0040_remove_prestamos_id_alter_prestamos_prestamo_id.py
from django.db import migrations

def forwards(apps, schema_editor):
    Prestamos = apps.get_model('appfinancia', 'Prestamos')
    Desembolsos = apps.get_model('appfinancia', 'Desembolsos')
    db_alias = schema_editor.connection.alias

    for p in Prestamos.objects.using(db_alias).all():
        desembolso_id = p.prestamo_id_id  # valor numérico del desembolso
        try:
            desembolso = Desembolsos.objects.using(db_alias).get(prestamo_id=desembolso_id)
        except Desembolsos.DoesNotExist:
            print(f"⚠️ Desembolso {desembolso_id} no existe. Saltando préstamo.")
            continue

        # Guardar todos los campos excepto 'id' y la FK vieja
        campos = {
            'cliente_id_id': p.cliente_id_id,
            'asesor_id_id': p.asesor_id_id,
            'aseguradora_id_id': p.aseguradora_id_id,
            'vendedor_id_id': p.vendedor_id_id,
            'tipo_tasa_id': p.tipo_tasa_id,
            'tasa': p.tasa,
            'valor': p.valor,
            'valor_cuota_1': p.valor_cuota_1,
            'valor_cuota_mensual': p.valor_cuota_mensual,
            'valor_seguro_mes': p.valor_seguro_mes,
            'tiene_fee': p.tiene_fee,
            'dia_cobro': p.dia_cobro,
            'plazo_en_meses': p.plazo_en_meses,
            'fecha_desembolso': p.fecha_desembolso,
            'fecha_vencimiento': p.fecha_vencimiento,
            'suspender_causacion': p.suspender_causacion,
            'fecha_suspension_causacion': p.fecha_suspension_causacion,
            'revocatoria': p.revocatoria,
            'fecha_revocatoria': p.fecha_revocatoria,
        }

        # Eliminar el préstamo antiguo
        p.delete(using=db_alias)
        # Crear el nuevo con la instancia de Desembolsos
        Prestamos.objects.using(db_alias).create(prestamo_id=desembolso, **campos)

def backwards(apps, schema_editor):
    # Opcional: lógica para revertir (compleja, omitida)
    pass

class Migration(migrations.Migration):
    dependencies = [
        ('appfinancia', '0039_alter_desembolsos_aseguradora_id_and_more'),
    ]
    operations = [
        migrations.RunPython(forwards, backwards),
    ]