# Generated by Django 5.2.7 on 2025-11-24 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0040_remove_prestamos_id_alter_prestamos_prestamo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamos',
            name='id',
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='prestamo_id',
            field=models.OneToOneField(db_column='prestamo_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='appfinancia.desembolsos'),
        ),
    ]
