# Generated by Django 5.2.7 on 2025-11-26 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0042_pagos_archivos_pagos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fechas_Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_proceso_actual', models.DateField(help_text='Fecha en la que se está procesando actualmente (día hábil).')),
                ('fecha_proceso_anterior', models.DateField(help_text='Fecha del último proceso realizado.')),
                ('fecha_proximo_proceso', models.DateField(help_text='Fecha esperada del próximo proceso.')),
                ('estado_sistema', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='ABIERTO', help_text='Controla si el sistema permite operaciones o solo consultas.', max_length=8)),
                ('modo_fecha_sistema', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATICO', 'Automático')], default='AUTOMATICO', help_text='Automático: se sincroniza con la fecha del sistema. Manual: editable.', max_length=10)),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización (sistema).')),
                ('cambiado_por', models.ForeignKey(editable=False, help_text='Usuario que realizó la última modificación.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fecha de Sistema',
                'verbose_name_plural': 'Fechas de Sistema',
            },
        ),
    ]
