# Generated by Django 5.2.7 on 2025-12-20 20:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0043_fechas_sistema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultasReportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas y Reportes',
                'permissions': [('puede_consultar_causacion', 'Puede acceder a la consulta de causación')],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detalle_Aplicacion_Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_aplicado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('componente', models.CharField(choices=[('CAPITAL', 'Capital'), ('INTERES', 'Interés'), ('SEGURO', 'Seguro'), ('GASTOS', 'Gastos'), ('EXCEDENTE', 'Excedente')], max_length=15)),
                ('fecha_aplicacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Detalle de Aplicación de Pago',
                'verbose_name_plural': 'Detalles de Aplicación de Pago',
            },
        ),
        migrations.CreateModel(
            name='InBox_PagosCabezal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, help_text='Seleccione el archivo a cargar', null=True, upload_to='pagos_archivos/')),
                ('nombre_archivo_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('formato', models.CharField(choices=[('1-FORMATO PSE', '1 - Formato PSE'), ('2-FORMATO ESTANDAR', '2 - Formato Estándar'), ('3-FORMATO EXTRACTO BANCOLOMBIA', '3 - Extracto Bancolombia')], max_length=30)),
                ('fecha_carga_archivo', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('banco_origen', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('registros_cargados', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('registros_rechazados', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('estado_proceso_archivo', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('A_PROCESAR', 'A procesar'), ('ANULADO', 'Anulado')], default='RECIBIDO', max_length=20)),
                ('observaciones', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'InBox Pagos',
                'verbose_name_plural': 'InBox Pagos',
                'ordering': ['-fecha_carga_archivo'],
            },
        ),
        migrations.CreateModel(
            name='InBox_PagosDetalle',
            fields=[
                ('pago_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lote_pse', models.BigIntegerField(blank=True, null=True)),
                ('fragmento_de', models.BigIntegerField(blank=True, null=True)),
                ('fecha_carga_archivo', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('banco_origen', models.CharField(blank=True, max_length=100)),
                ('cuenta_bancaria', models.CharField(blank=True, max_length=100)),
                ('tipo_cuenta_bancaria', models.CharField(blank=True, choices=[('AHORROS', 'Ahorros'), ('CORRIENTE', 'Corriente')], max_length=9)),
                ('canal_red_pago', models.CharField(blank=True, max_length=100)),
                ('ref_bancaria', models.CharField(blank=True, max_length=100)),
                ('ref_red', models.CharField(blank=True, max_length=100)),
                ('ref_cliente_1', models.CharField(blank=True, max_length=200)),
                ('ref_cliente_2', models.CharField(blank=True, max_length=200)),
                ('ref_cliente_3', models.CharField(blank=True, max_length=200)),
                ('estado_transaccion_reportado', models.CharField(blank=True, max_length=20)),
                ('clase_movimiento', models.CharField(blank=True, choices=[('PAGO_PSE', 'Pago PSE'), ('PAGO_BANCOL', 'Pago Bancolombia'), ('ABONO_PSE', 'Abono PSE'), ('EXLUIDO', 'Excludio')], max_length=30, null=True)),
                ('estado_fragmentacion', models.CharField(blank=True, choices=[('NO_REQUIERE', 'No requiere'), ('A_FRAMENTAR', 'A fragmentar'), ('FRAGMENTADO', 'Fragmentado')], max_length=20)),
                ('cliente_id_reportado', models.CharField(blank=True, max_length=20)),
                ('prestamo_id_reportado', models.CharField(blank=True, max_length=20)),
                ('poliza_id_reportado', models.CharField(blank=True, max_length=20)),
                ('poliza_id_real', models.CharField(blank=True, max_length=20)),
                ('fecha_pago', models.DateField()),
                ('fecha_conciliacion', models.DateTimeField(blank=True, null=True)),
                ('estado_pago', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('A_PROCESAR', 'A procesar'), ('ANULADO', 'Anulado'), ('CONFIRMADO', 'Confirmado'), ('A_NORMALIZAR', 'A regularizar'), ('EXCLUIDO', 'Excludio')], max_length=20, null=True)),
                ('estado_conciliacion', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('observaciones', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'InBox Pago Recibido',
                'verbose_name_plural': 'InBox Pagos Recibidos',
            },
        ),
        migrations.CreateModel(
            name='Migrados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestamo_id', models.BigIntegerField(help_text='ID del préstamo migrado (coincide con Desembolsos.prestamo_id)')),
                ('origen_migracion', models.CharField(blank=True, help_text="Nombre del archivo Excel de origen (ej. 'aresmig.xlsx')", max_length=100, null=True)),
                ('fecha_migracion', models.DateField(auto_now_add=True, help_text='Fecha en que se realizó la migración')),
                ('hora_migracion', models.DateTimeField(auto_now_add=True, help_text='Hora exacta en que se registró la migración')),
            ],
            options={
                'verbose_name': 'Préstamo Migrado',
                'verbose_name_plural': 'Préstamos Migrados',
                'ordering': ['-fecha_migracion', '-hora_migracion'],
            },
        ),
        migrations.RemoveField(
            model_name='pagos_archivos',
            name='creado_por',
        ),
        migrations.AlterField(
            model_name='pagos',
            name='nombre_archivo_id',
            field=models.CharField(db_index=True, help_text='Identificador del archivo de origen (no es ForeignKey)', max_length=200),
        ),
        migrations.AlterModelOptions(
            name='pagos',
            options={'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterUniqueTogether(
            name='historia_prestamos',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='valor_aplicado_acreedores',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='valor_aplicado_capital',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='valor_aplicado_gastos',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='valor_aplicado_intereses',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='valor_aplicado_otros',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='valor_aplicado_seguros',
        ),
        migrations.AddField(
            model_name='clientes',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='historia_prestamos',
            name='capital_aplicado_periodo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto total de capital aplicado en este período', max_digits=15),
        ),
        migrations.AddField(
            model_name='historia_prestamos',
            name='numero_asiento_contable',
            field=models.PositiveIntegerField(default=0, help_text='Número único que identifica el bloque de registros de un mismo pago'),
        ),
        migrations.AddField(
            model_name='historia_prestamos',
            name='numero_pago_referencia',
            field=models.CharField(blank=True, help_text='Referencia del pago que generó este cierre de periodo', max_length=50),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='direccion',
            field=models.CharField(help_text='Dirección del cliente (máximo 120 caracteres).', max_length=120),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(help_text='Correo electrónico del cliente (máximo 120 caracteres).', max_length=120, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='tipo_id',
            field=models.ForeignKey(help_text='Tipo de identificación (ej. CC, TI, CE, PA, NIT).', on_delete=django.db.models.deletion.PROTECT, to='appfinancia.tipos_identificacion'),
        ),
        migrations.AlterField(
            model_name='historia_prestamos',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Cuota Pendiente'), ('PAGADA', 'Pagada'), ('CANCELADO', 'Cancelado'), ('MOROSO', 'Moroso'), ('TRANSACCION', 'Transaccion')], default='PENDIENTE', max_length=14),
        ),
        migrations.AlterField(
            model_name='historia_prestamos',
            name='fecha_efectiva',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='banco_origen',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='canal_red_pago',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='cliente_id_real',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='cliente_id_reportado',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='creado_por',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='cuenta_bancaria',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='estado_conciliacion',
            field=models.CharField(blank=True, choices=[('cliente o prestamo no existe', 'Cliente o préstamo no existe'), ('prestamo_cancelado', 'Préstamo cancelado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='estado_pago',
            field=models.CharField(choices=[('Recibido', 'Recibido'), ('pendiente', 'Pendiente'), ('rechazado', 'Rechazado'), ('conciliado', 'Conciliado'), ('aplicado', 'Aplicado'), ('reversado', 'Reversado')], default='Recibido', max_length=12),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='estado_transaccion_reportado',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='fecha_aplicacion_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='fecha_carga_archivo',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='fecha_conciliacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='fecha_pago',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='hora_pago',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='pago_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='poliza_id_real',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='poliza_id_reportado',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='prestamo_id_real',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='prestamo_id_reportado',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='ref_bancaria',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='ref_cliente_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='ref_cliente_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='ref_cliente_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='ref_red',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='tipo_cuenta_bancaria',
            field=models.CharField(blank=True, choices=[('AHORROS', 'Ahorros'), ('CORRIENTE', 'Corriente')], max_length=9),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterUniqueTogether(
            name='historia_prestamos',
            unique_together={('prestamo_id', 'fecha_efectiva', 'ordinal_interno', 'fecha_proceso', 'numero_operacion')},
        ),
        migrations.AddIndex(
            model_name='historia_prestamos',
            index=models.Index(fields=['numero_asiento_contable'], name='appfinancia_numero__062496_idx'),
        ),
        migrations.AddIndex(
            model_name='historia_prestamos',
            index=models.Index(fields=['prestamo_id', 'numero_asiento_contable'], name='appfinancia_prestam_ac2a50_idx'),
        ),
        migrations.CreateModel(
            name='ConsultasReportesProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Consulta de Causación',
                'verbose_name_plural': 'Consultas y Reportes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('appfinancia.consultasreportes',),
        ),
        migrations.AddField(
            model_name='detalle_aplicacion_pago',
            name='historia_prestamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appfinancia.historia_prestamos'),
        ),
        migrations.AddField(
            model_name='detalle_aplicacion_pago',
            name='pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_aplicacion', to='appfinancia.pagos'),
        ),
        migrations.AddField(
            model_name='inbox_pagoscabezal',
            name='creado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inbox_pagosdetalle',
            name='cliente_id_real',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appfinancia.clientes'),
        ),
        migrations.AddField(
            model_name='inbox_pagosdetalle',
            name='creado_por',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inbox_pagosdetalle',
            name='nombre_archivo_id',
            field=models.ForeignKey(help_text='Archivo de origen', on_delete=django.db.models.deletion.PROTECT, to='appfinancia.inbox_pagoscabezal', to_field='nombre_archivo_id'),
        ),
        migrations.AddField(
            model_name='inbox_pagosdetalle',
            name='prestamo_id_real',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appfinancia.prestamos'),
        ),
        migrations.DeleteModel(
            name='Pagos_Archivos',
        ),
    ]
