# Generated by Django 5.2.7 on 2025-12-31 01:44

import django.core.serializers.json
import django.db.models.deletion
import smart_selects.db_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0044_consultasreportes_detalle_aplicacion_pago_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fechas_sistema',
            options={'verbose_name': 'Fecha de Sistema', 'verbose_name_plural': 'Fecha de Sistema'},
        ),
        migrations.AlterModelOptions(
            name='inbox_pagoscabezal',
            options={'ordering': ['-fecha_carga_archivo'], 'verbose_name': 'InBox archivos de Pagos', 'verbose_name_plural': 'InBox archivos de Pagos'},
        ),
        migrations.AlterModelOptions(
            name='inbox_pagosdetalle',
            options={'verbose_name': 'InBox detalle de pagos', 'verbose_name_plural': 'InBox detalle de pagos'},
        ),
        migrations.AlterModelOptions(
            name='pagos',
            options={'verbose_name': 'Pagos confirmados', 'verbose_name_plural': 'Pagos confirmados'},
        ),
        migrations.AlterField(
            model_name='clientes',
            name='municipio',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='departamento', chained_model_field='departamento', help_text='Municipio del cliente. Debe pertenecer al departamento seleccionado.', on_delete=django.db.models.deletion.CASCADE, to='appfinancia.municipios'),
        ),
        migrations.AlterField(
            model_name='fechas_sistema',
            name='cambiado_por',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fechas_sistema',
            name='estado_sistema',
            field=models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=8),
        ),
        migrations.AlterField(
            model_name='fechas_sistema',
            name='fecha_proceso_actual',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fechas_sistema',
            name='fecha_proceso_anterior',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fechas_sistema',
            name='fecha_proximo_proceso',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fechas_sistema',
            name='fecha_ultima_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fechas_sistema',
            name='modo_fecha_sistema',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATICO', 'Automático')], default='AUTOMATICO', max_length=10),
        ),
        migrations.AlterField(
            model_name='inbox_pagosdetalle',
            name='clase_movimiento',
            field=models.CharField(blank=True, choices=[('PAGO_PSE', 'Pago PSE'), ('PAGO_BANCOL', 'Pago Bancolombia'), ('LOTE_PSE', 'Lote PSE'), ('EXLUIDO', 'Excludio')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='estado_pago',
            field=models.CharField(choices=[('CONCILIADO', 'Conciliado'), ('APLICADO', 'Aplicado'), ('REVERSADO', 'Reversado')], default='Recibido', max_length=12),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='pago_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ComprobantePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_json', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('prestamo_id', models.PositiveIntegerField(db_index=True)),
                ('cliente_id', models.PositiveIntegerField(db_index=True)),
                ('email_cliente', models.EmailField(blank=True, max_length=254)),
                ('enviado_email', models.BooleanField(default=False)),
                ('fecha_envio_email', models.DateTimeField(blank=True, null=True)),
                ('excluir_envio_automatico', models.BooleanField(default=False, help_text='Si está marcado, este comprobante NO se enviará en envíos masivos automáticos.')),
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comprobante', to='appfinancia.pagos')),
            ],
            options={
                'verbose_name': 'Comprobante de Pago',
                'verbose_name_plural': 'Comprobantes de Pago',
                'indexes': [models.Index(fields=['prestamo_id'], name='appfinancia_prestam_e72e75_idx'), models.Index(fields=['cliente_id'], name='appfinancia_cliente_f2e45e_idx'), models.Index(fields=['cliente_id', 'fecha_generacion'], name='appfinancia_cliente_276f90_idx'), models.Index(fields=['enviado_email', 'excluir_envio_automatico'], name='appfinancia_enviado_d1e9c0_idx')],
            },
        ),
    ]
