# Generated by Django 5.2.7 on 2025-11-28 04:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0044_remove_pagos_archivos_creado_por_delete_pagos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos_Archivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo_id', models.CharField(help_text='Nombre único del archivo (sin extensión duplicada).', max_length=100, unique=True)),
                ('formato', models.CharField(choices=[('1-FORMATO PSE', '1 - Formato PSE'), ('2-FORMATO ESTANDAR', '2 - Formato Estándar'), ('3-FORMATO EXTRACTO BANCOLOMBIA', '3 - Extracto Bancolombia')], help_text='Formato esperado del archivo de pagos.', max_length=30)),
                ('fecha_carga_archivo', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Fecha y hora de carga automática.')),
                ('banco_origen', models.CharField(blank=True, help_text='Nombre del banco emisor del archivo (opcional).', max_length=100, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, help_text='Valor total consolidado del archivo.', max_digits=15)),
                ('registros_cargados', models.PositiveSmallIntegerField(default=0, editable=False, help_text='Número de registros procesados exitosamente.')),
                ('registros_rechazados', models.PositiveSmallIntegerField(default=0, editable=False, help_text='Número de registros rechazados durante la validación.')),
                ('estado_proceso_archivo', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('PROCESADO', 'Procesado'), ('ANULADO', 'Anulado')], default='RECIBIDO', help_text='Estado actual del procesamiento del archivo.', max_length=10)),
                ('observaciones', models.CharField(blank=True, help_text='Notas adicionales (máx. 200 caracteres).', max_length=200)),
                ('creado_por', models.ForeignKey(editable=False, help_text='Usuario que cargó el archivo.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo de Pagos',
                'verbose_name_plural': 'Archivos de Pagos',
                'ordering': ['-fecha_carga_archivo'],
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('pago_id', models.BigAutoField(editable=False, help_text='Numerador secuencial del sistema.', primary_key=True, serialize=False)),
                ('fecha_carga_archivo', models.DateTimeField(editable=False, help_text='Fecha del momento de la carga del archivo.')),
                ('banco_origen', models.CharField(blank=True, help_text='Nombre de la entidad financiera que recauda el pago.', max_length=100)),
                ('cuenta_bancaria', models.CharField(blank=True, help_text='Número de la cuenta bancaria de Credi Finanza donde se recibió el pago.', max_length=100)),
                ('tipo_cuenta_bancaria', models.CharField(blank=True, choices=[('AHORROS', 'Ahorros'), ('CORRIENTE', 'Corriente')], help_text='Tipo de cuenta bancaria.', max_length=9)),
                ('canal_red_pago', models.CharField(blank=True, help_text='Medio de pago: PSE, EFECTY, TRANSFERENCIA, BALOTO, etc.', max_length=100)),
                ('ref_bancaria', models.CharField(blank=True, help_text='Referencia del banco que recauda el pago (ej. número CUS).', max_length=100)),
                ('ref_red', models.CharField(blank=True, help_text='Nombre de la red por donde se realiza el pago (ej. Punto Red).', max_length=100)),
                ('ref_cliente_1', models.CharField(blank=True, help_text='Referencia que escribe el cliente (1).', max_length=100)),
                ('ref_cliente_2', models.CharField(blank=True, help_text='Referencia que escribe el cliente (2).', max_length=100)),
                ('ref_cliente_3', models.CharField(blank=True, help_text='Referencia que escribe el cliente (3).', max_length=100)),
                ('estado_transaccion_reportado', models.CharField(blank=True, help_text="Estado reportado por el banco origen (ej. 'Exitoso', 'Anulado').", max_length=20)),
                ('cliente_id_reportado', models.CharField(blank=True, help_text='Identificación del cliente que realiza el pago.', max_length=20)),
                ('prestamo_id_reportado', models.CharField(blank=True, help_text='Identificación del préstamo a pagar.', max_length=20)),
                ('poliza_id_reportado', models.CharField(blank=True, help_text='Número de la póliza a aplicar el pago.', max_length=20)),
                ('cliente_id_real', models.BigIntegerField(blank=True, help_text='Identificación real del cliente (relacionado con Clientes).', null=True)),
                ('prestamo_id_real', models.BigIntegerField(blank=True, help_text='ID real del préstamo (relacionado con Desembolsos.prestamo_id).', null=True)),
                ('poliza_id_real', models.CharField(blank=True, help_text='Número real de la póliza aplicada.', max_length=20)),
                ('fecha_pago', models.DateField(help_text='Fecha real del pago (aaaa/mm/dd).')),
                ('hora_pago', models.TimeField(help_text='Hora real del pago (hh:mm:ss).')),
                ('fecha_aplicacion_pago', models.DateTimeField(blank=True, help_text='Fecha y hora en que se aplicó el pago al préstamo.', null=True)),
                ('fecha_conciliacion', models.DateTimeField(blank=True, help_text='Fecha y hora de la conciliación automática o manual.', null=True)),
                ('estado_pago', models.CharField(choices=[('Recibido', 'Recibido'), ('pendiente', 'Pendiente'), ('rechazado', 'Rechazado'), ('conciliado', 'Conciliado'), ('aplicado', 'Aplicado'), ('reversado', 'Reversado'), ('acreedores', 'Acreedores')], default='Recibido', help_text='Estado actual del pago en el sistema.', max_length=12)),
                ('estado_conciliacion', models.CharField(blank=True, choices=[('cliente o prestamo no existe', 'Cliente o préstamo no existe'), ('prestamo_cancelado', 'Préstamo cancelado')], help_text='Motivo de rechazo en conciliación automática.', max_length=30)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, help_text='Valor total recibido del pago.', max_digits=15)),
                ('valor_aplicado_capital', models.DecimalField(decimal_places=2, default=0, help_text='Valor aplicado a capital.', max_digits=15)),
                ('valor_aplicado_intereses', models.DecimalField(decimal_places=2, default=0, help_text='Valor aplicado a intereses.', max_digits=15)),
                ('valor_aplicado_seguros', models.DecimalField(decimal_places=2, default=0, help_text='Valor aplicado a seguros.', max_digits=15)),
                ('valor_aplicado_gastos', models.DecimalField(decimal_places=2, default=0, help_text='Valor aplicado a gastos.', max_digits=15)),
                ('valor_aplicado_acreedores', models.DecimalField(decimal_places=2, default=0, help_text='Valor aplicado a acreedores.', max_digits=15)),
                ('valor_aplicado_otros', models.DecimalField(decimal_places=2, default=0, help_text='Valor aplicado a otros conceptos.', max_digits=15)),
                ('observaciones', models.CharField(blank=True, help_text='Notas adicionales sobre el pago.', max_length=200)),
                ('creado_por', models.ForeignKey(editable=False, help_text='Usuario que procesó el pago.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('nombre_archivo_id', models.ForeignKey(db_column='nombre_archivo_id', help_text='Identificador único del archivo de pagos.', on_delete=django.db.models.deletion.PROTECT, to='appfinancia.pagos_archivos', to_field='nombre_archivo_id')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago', '-hora_pago', '-pago_id'],
            },
        ),
    ]
