# Generated by Django 5.2.7 on 2026-01-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0045_alter_fechas_sistema_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantepago',
            name='cliente_id',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='comprobantepago',
            name='prestamo_id',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
