# Generated by Django 5.2.7 on 2026-01-08 18:51

import appfinancia.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0046_alter_comprobantepago_cliente_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadesFinancieras',
            fields=[
                ('nit', models.BigIntegerField(help_text='Ingrese el NIT seguido del dígito de verificación, sin espacios ni guiones (Ej: 8600000001).', primary_key=True, serialize=False, validators=[appfinancia.utils.validar_nit])),
                ('nombre_corto', models.CharField(max_length=15)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('nombre_contacto', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('HABILITADO', 'HABILITADO'), ('DESHABILITADO', 'DESHABILITADO')], default='HABILITADO', max_length=13)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Entidad Financiera',
                'verbose_name_plural': 'Entidades Financieras',
                'ordering': ['nombre_corto'],
            },
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='tipo_tasa',
            field=models.CharField(blank=True, choices=[('CON SEGURO', 'CON SEGURO'), ('SIN SEGURO', 'SIN SEGURO')], help_text='Seleccione el tipo de tasa', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='tipo_tasa',
            field=models.CharField(blank=True, choices=[('CON SEGURO', 'CON SEGURO'), ('SIN SEGURO', 'SIN SEGURO')], help_text='Tipo de tasa aplicada.', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='vendedor_id',
            field=models.ForeignKey(help_text='Codigo de venta', on_delete=django.db.models.deletion.PROTECT, to='appfinancia.vendedores'),
        ),
        migrations.AddField(
            model_name='desembolsos',
            name='beneficiario_seguro',
            field=models.ForeignKey(blank=True, help_text='Entidad financiera que figura como beneficiaria en la póliza.', null=True, on_delete=django.db.models.deletion.PROTECT, to='appfinancia.entidadesfinancieras', verbose_name='Beneficiario Seguro (Entidad)'),
        ),
        migrations.DeleteModel(
            name='Tasas',
        ),
    ]
