# Generated by Django 5.2.7 on 2026-01-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0047_entidadesfinancieras_alter_desembolsos_tipo_tasa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tasa', models.CharField(choices=[('CON SEGURO', 'CON SEGURO'), ('SIN SEGURO', 'SIN SEGURO')], help_text="Tipo de tasa: 'CON SEGURO' o 'SIN SEGURO'.", max_length=15)),
                ('fecha_aplica', models.DateField(help_text='Fecha a partir de la cual rige esta tasa.')),
                ('tasa', models.DecimalField(decimal_places=2, help_text='Valor de la tasa mensual.', max_digits=4)),
            ],
            options={
                'verbose_name': 'Tasa',
                'verbose_name_plural': 'Tasas',
                'ordering': ['-fecha_aplica'],
                'unique_together': {('tipo_tasa', 'fecha_aplica')},
            },
        ),
    ]
