# Generated by Django 5.2.7 on 2026-01-09 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0048_tasas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desembolsos',
            name='beneficiario_seguro',
        ),
        migrations.AddField(
            model_name='desembolsos',
            name='entidad_onerosa',
            field=models.ForeignKey(blank=True, help_text='Seleccione la entidad financiera beneficiaria.', null=True, on_delete=django.db.models.deletion.PROTECT, to='appfinancia.entidadesfinancieras', verbose_name='Entidad Onerosa'),
        ),
        migrations.AddField(
            model_name='desembolsos',
            name='ofrece_cuota_inicial',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', help_text='Indique si el cliente ofrece pagar cuota inicial.', max_length=2),
        ),
        migrations.AddField(
            model_name='desembolsos',
            name='tiene_oneroso',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', help_text='Indique si el seguro tiene beneficiario oneroso.', max_length=2, verbose_name='¿Tiene Oneroso?'),
        ),
        migrations.AddField(
            model_name='desembolsos',
            name='valor_cuota_inicial',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor de la cuota Inicial', max_digits=15),
        ),
        migrations.AddField(
            model_name='prestamos',
            name='entidad_onerosa',
            field=models.ForeignKey(blank=True, help_text='Seleccione la entidad financiera beneficiaria.', null=True, on_delete=django.db.models.deletion.PROTECT, to='appfinancia.entidadesfinancieras', verbose_name='Entidad Onerosa'),
        ),
        migrations.AddField(
            model_name='prestamos',
            name='ofrece_cuota_inicial',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', help_text='Indique si el cliente ofrece pagar cuota inicial.', max_length=2),
        ),
        migrations.AddField(
            model_name='prestamos',
            name='tiene_oneroso',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', help_text='Indique si el seguro tiene beneficiario oneroso.', max_length=2, verbose_name='¿Tiene Oneroso?'),
        ),
        migrations.AddField(
            model_name='prestamos',
            name='valor_cuota_inicial',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor de la cuota Inicial', max_digits=15),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='numero_transaccion_cuota_1',
            field=models.CharField(blank=True, help_text='Cuota Inicial / Cuota 1', max_length=10, verbose_name='Pago_Id:'),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='plazo_en_meses',
            field=models.PositiveSmallIntegerField(default=10, help_text='cantidad de cuotas mensuales', verbose_name='cantidad cuotas'),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor de la Póliza', max_digits=15),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='valor_cuota_1',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cuota Inicial / Cuota 1', max_digits=15, verbose_name=''),
        ),
    ]
