# Generated by Django 5.2.7 on 2025-11-28 19:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0048_remove_pagos_archivos_creado_por_delete_pagos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos_Archivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo_id', models.CharField(help_text='Nombre único del archivo (sin extensión duplicada).', max_length=100, unique=True)),
                ('formato', models.CharField(choices=[('1-FORMATO PSE', '1 - Formato PSE'), ('2-FORMATO ESTANDAR', '2 - Formato Estándar'), ('3-FORMATO EXTRACTO BANCOLOMBIA', '3 - Extracto Bancolombia')], max_length=30)),
                ('fecha_carga_archivo', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('banco_origen', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('registros_cargados', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('registros_rechazados', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('estado_proceso_archivo', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('PROCESADO', 'Procesado'), ('ANULADO', 'Anulado')], default='RECIBIDO', max_length=10)),
                ('observaciones', models.CharField(blank=True, max_length=200)),
                ('creado_por', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo de Pagos',
                'verbose_name_plural': 'Archivos de Pagos',
                'ordering': ['-fecha_carga_archivo'],
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('pago_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_carga_archivo', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('banco_origen', models.CharField(blank=True, max_length=100)),
                ('cuenta_bancaria', models.CharField(blank=True, max_length=100)),
                ('tipo_cuenta_bancaria', models.CharField(blank=True, choices=[('AHORROS', 'Ahorros'), ('CORRIENTE', 'Corriente')], max_length=9)),
                ('canal_red_pago', models.CharField(blank=True, max_length=100)),
                ('ref_bancaria', models.CharField(blank=True, max_length=100)),
                ('ref_red', models.CharField(blank=True, max_length=100)),
                ('ref_cliente_1', models.CharField(blank=True, max_length=100)),
                ('ref_cliente_2', models.CharField(blank=True, max_length=100)),
                ('ref_cliente_3', models.CharField(blank=True, max_length=100)),
                ('estado_transaccion_reportado', models.CharField(blank=True, max_length=20)),
                ('cliente_id_reportado', models.CharField(blank=True, max_length=20)),
                ('prestamo_id_reportado', models.CharField(blank=True, max_length=20)),
                ('poliza_id_reportado', models.CharField(blank=True, max_length=20)),
                ('cliente_id_real', models.BigIntegerField(blank=True, null=True)),
                ('prestamo_id_real', models.BigIntegerField(blank=True, null=True)),
                ('poliza_id_real', models.CharField(blank=True, max_length=20)),
                ('fecha_pago', models.DateField()),
                ('hora_pago', models.TimeField()),
                ('fecha_aplicacion_pago', models.DateTimeField(blank=True, null=True)),
                ('fecha_conciliacion', models.DateTimeField(blank=True, null=True)),
                ('estado_pago', models.CharField(choices=[('Recibido', 'Recibido'), ('pendiente', 'Pendiente'), ('rechazado', 'Rechazado'), ('conciliado', 'Conciliado'), ('aplicado', 'Aplicado'), ('reversado', 'Reversado'), ('acreedores', 'Acreedores')], default='Recibido', max_length=12)),
                ('estado_conciliacion', models.CharField(blank=True, choices=[('cliente o prestamo no existe', 'Cliente o préstamo no existe'), ('prestamo_cancelado', 'Préstamo cancelado')], max_length=30)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_aplicado_capital', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_aplicado_intereses', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_aplicado_seguros', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_aplicado_gastos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_aplicado_acreedores', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_aplicado_otros', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('observaciones', models.CharField(blank=True, max_length=200)),
                ('creado_por', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('nombre_archivo_id', models.ForeignKey(help_text='Archivo de origen', on_delete=django.db.models.deletion.PROTECT, to='appfinancia.pagos_archivos', to_field='nombre_archivo_id')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago', '-pago_id'],
            },
        ),
    ]
