# Generated by Django 5.2.7 on 2026-01-09 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0049_remove_desembolsos_beneficiario_seguro_and_more'),
    ]
    operations = [
        migrations.AddField(
            model_name='desembolsos',
            name='tasa_mes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='prestamos',
            name='tasa_mes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='tipo_tasa',
            field=models.CharField(blank=True, choices=[('CON SEGURO', 'CON SEGURO'), ('SIN SEGURO', 'SIN SEGURO'), ('ESPECIAL', 'ESPECIAL')], help_text='Seleccione el tipo de tasa', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tasas',
            name='tipo_tasa',
            field=models.CharField(choices=[('CON SEGURO', 'CON SEGURO'), ('SIN SEGURO', 'SIN SEGURO'), ('ESPECIAL', 'ESPECIAL')], help_text="Tipo de tasa: 'CON SEGURO' o 'SIN SEGURO'.", max_length=15),
        ),
    ]
