# Generated by Django 5.2.7 on 2025-11-26 21:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0050_alter_pagos_archivos_creado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia_prestamos',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Cuota Pendiente'), ('PAGADA', 'Pagada'), ('CANCELADO', 'Cancelado'), ('MOROSO', 'Moroso'), ('TRANSACCION', 'Transaccion')], default='PENDIENTE', max_length=14),
        ),
        migrations.CreateModel(
            name='Acumulado_Interes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(help_text='Fecha inicial del período')),
                ('fecha_fin', models.DateField(help_text='Fecha final del período (inclusive)')),
                ('saldo_capital', models.DecimalField(decimal_places=2, help_text='Saldo de capital constante durante el período', max_digits=15)),
                ('tasa_diaria', models.DecimalField(decimal_places=8, max_digits=10)),
                ('dias', models.IntegerField(help_text='Número de días en el período')),
                ('interes_acumulado', models.DecimalField(decimal_places=2, help_text='Interés total causado en el período', max_digits=15)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appfinancia.prestamos')),
            ],
            options={
                'verbose_name': 'Acumulado de Interés',
                'verbose_name_plural': 'Acumulados de Interés',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Detalle_Aplicacion_Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_aplicado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('componente', models.CharField(choices=[('CAPITAL', 'Capital'), ('INTERES', 'Interés'), ('SEGURO', 'Seguro'), ('GASTOS', 'Gastos'), ('EXCEDENTE', 'Excedente')], max_length=15)),
                ('fecha_aplicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('historia_prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appfinancia.historia_prestamos')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_aplicacion', to='appfinancia.pagos')),
            ],
            options={
                'verbose_name': 'Detalle de Aplicación de Pago',
                'verbose_name_plural': 'Detalles de Aplicación de Pago',
            },
        ),
    ]
