# Generated by Django 5.2.7 on 2026-01-12 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0050_desembolsos_tasa_mes_prestamos_tasa_mes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraReversiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reversion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(max_length=100)),
                ('proceso', models.CharField(max_length=100)),
                ('objeto_id', models.CharField(max_length=50)),
                ('asiento_original', models.CharField(max_length=50, null=True)),
                ('asiento_reversion', models.CharField(max_length=50, null=True)),
                ('motivo', models.TextField()),
                ('dump_datos_anteriores', models.JSONField()),
            ],
            options={
                'verbose_name': 'Bitácora de Reversión',
                'verbose_name_plural': 'Bitácora de Reversiones',
            },
        ),
        migrations.AlterModelOptions(
            name='desembolsos',
            options={'ordering': ['-fecha_desembolso'], 'permissions': [('can_revert_desembolso', 'Puede revertir un desembolso ya procesado')], 'verbose_name': 'Desembolso', 'verbose_name_plural': 'Desembolsos'},
        ),
        migrations.AlterModelOptions(
            name='pagos',
            options={'permissions': [('can_revert_pago', 'Puede revertir aplicaciones de pago')], 'verbose_name': 'Pagos confirmados', 'verbose_name_plural': 'Pagos confirmados'},
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='numero_transaccion_cuota_1',
            field=models.CharField(blank=True, help_text='Cuota Inicial/Cuota 1', max_length=10, verbose_name='Pago_Id'),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor de la Póliza', max_digits=15, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='valor_cuota_1',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cuota 1', max_digits=15, verbose_name='Cuota 1'),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='valor_cuota_mensual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cuota mensual calculada', max_digits=15),
        ),
    ]
