# Generated by Django 5.2.7 on 2025-11-28 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0051_pagos_archivos_pagos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos_archivos',
            name='creado_por',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que registró el comentario.', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
