# Generated by Django 5.2.7 on 2025-11-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0051_alter_historia_prestamos_estado_acumulado_interes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia_prestamos',
            name='fecha_efectiva',
            field=models.DateField(blank=True, null=True),
        ),
    ]
