# Generated by Django 5.2.7 on 2026-01-14 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0051_bitacorareversiones_alter_desembolsos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desembolsos',
            name='aseguradora_id',
            field=models.ForeignKey(db_column='aseguradora_id', on_delete=django.db.models.deletion.PROTECT, to='appfinancia.aseguradoras'),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='asesor_id',
            field=models.ForeignKey(db_column='asesor_id', on_delete=django.db.models.deletion.PROTECT, to='appfinancia.asesores'),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='vendedor_id',
            field=models.ForeignKey(db_column='vendedor_id', help_text='Codigo de venta', on_delete=django.db.models.deletion.PROTECT, to='appfinancia.vendedores'),
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='aseguradora_id',
            field=models.ForeignKey(blank=True, db_column='aseguradora_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='appfinancia.aseguradoras'),
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='asesor_id',
            field=models.ForeignKey(db_column='asesor_id', on_delete=django.db.models.deletion.PROTECT, to='appfinancia.asesores'),
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='vendedor_id',
            field=models.ForeignKey(blank=True, db_column='vendedor_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='appfinancia.vendedores'),
        ),
    ]
