# Generated by Django 5.2.7 on 2026-01-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0052_alter_desembolsos_aseguradora_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamos',
            name='estado',
            field=models.CharField(choices=[('ELABORACION', 'En Elaboración'), ('ACTIVO', 'Activo'), ('REVERTIDO', 'Revertido'), ('SIN CAUSACION', 'Sin Causacion'), ('FINALIZADO', 'Finalizado / Pagado'), ('ANULADO', 'Anulado')], default='ELABORACION', max_length=15),
        ),
    ]
