# Generated by Django 5.2.7 on 2025-12-02 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0052_alter_pagos_archivos_creado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_aplicacion_pago',
            name='historia_prestamo',
        ),
        migrations.RemoveField(
            model_name='detalle_aplicacion_pago',
            name='pago',
        ),
        migrations.DeleteModel(
            name='Acumulado_Interes',
        ),
        migrations.DeleteModel(
            name='Detalle_Aplicacion_Pago',
        ),
    ]
