# Generated by Django 5.2.7 on 2025-12-02 23:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0053_remove_detalle_aplicacion_pago_historia_prestamo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractoBancario',
            fields=[
                ('nombre_archivo_id', models.CharField(help_text='Nombre del archivo PDF subido.', max_length=200, primary_key=True, serialize=False, verbose_name='Nombre del Archivo (ID)')),
                ('empresa', models.CharField(max_length=60)),
                ('nit', models.CharField(max_length=16)),
                ('numero_cuenta', models.CharField(max_length=12)),
                ('tipo_de_cuenta', models.CharField(max_length=20)),
                ('fecha_hora_actual', models.DateTimeField()),
                ('fecha_hora_consulta', models.DateTimeField()),
                ('fecha_carga_archivo', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('saldo_efectivo_actual', models.DecimalField(decimal_places=2, max_digits=15)),
                ('saldo_en_canje_actual', models.DecimalField(decimal_places=2, max_digits=15)),
                ('saldo_total_actual', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estado_proceso_archivo', models.CharField(choices=[('RECIBIDO', 'Recibido - Pendiente de Conciliar'), ('A_CONCILIAR', 'A Conciliar'), ('ANULADO', 'Anulado')], default='RECIBIDO', max_length=12)),
                ('archivo_pdf', models.FileField(upload_to='extractos_bancarios/')),
                ('creado_por', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Extracto Bancario',
                'verbose_name_plural': 'Extractos Bancarios',
            },
        ),
        migrations.CreateModel(
            name='ExtractoBancarioMovimientos',
            fields=[
                ('movimiento_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_movimiento', models.DateField()),
                ('descripcion', models.CharField(max_length=60)),
                ('sucursal_canal', models.CharField(blank=True, max_length=60)),
                ('referencia_1', models.CharField(blank=True, max_length=60)),
                ('referencia_2', models.CharField(blank=True, max_length=60)),
                ('documento', models.CharField(blank=True, max_length=60)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estado_movimiento', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('ANULADO', 'Anulado'), ('A_CONCILIAR', 'A Conciliar'), ('CONCILIADO', 'Conciliado')], default='RECIBIDO', max_length=12)),
                ('clase_movimiento', models.CharField(choices=[('PAGO_DIRECTO_CLIENTE', 'Pago Directo Cliente'), ('ABONO_PSE', 'Abono PSE'), ('OTROS', 'Otros')], default='OTROS', max_length=25)),
                ('cliente_id_real', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appfinancia.clientes')),
                ('nombre_archivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='appfinancia.extractobancario', verbose_name='Archivo de Origen')),
                ('prestamo_id_real', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appfinancia.prestamos')),
            ],
            options={
                'verbose_name': 'Movimiento de Extracto',
                'verbose_name_plural': 'Movimientos de Extracto',
                'ordering': ['fecha_movimiento', 'movimiento_id'],
            },
        ),
    ]
