# Generated by Django 5.2.7 on 2026-01-20 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0053_prestamos_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagosCuotaInicial',
            fields=[
            ],
            options={
                'verbose_name': 'InBox Pago para Regularizar',
                'verbose_name_plural': 'InBox Pagos para Regularizar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('appfinancia.inbox_pagosdetalle',),
        ),
        migrations.CreateModel(
            name='PagosParaRegularizar',
            fields=[
            ],
            options={
                'verbose_name': 'Pagos: 2.Gestión de pagos',
                'verbose_name_plural': 'Pagos: 2.Gestión de pagos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('appfinancia.inbox_pagosdetalle',),
        ),
        migrations.AlterModelOptions(
            name='fechas_sistema',
            options={'verbose_name': 'Parámetros Sistema', 'verbose_name_plural': 'Parámetros Sistema'},
        ),
        migrations.AlterModelOptions(
            name='inbox_pagoscabezal',
            options={'ordering': ['-fecha_carga_archivo'], 'verbose_name': 'Pagos: 1.Inbox de Archivos', 'verbose_name_plural': 'Pagos: 1.Inbox de Archivos'},
        ),
        migrations.AlterModelOptions(
            name='inbox_pagosdetalle',
            options={'verbose_name': 'Pagos: 4.Consultas', 'verbose_name_plural': 'Pagos: 4.Consultas'},
        ),
        migrations.AlterModelOptions(
            name='pagos',
            options={'permissions': [('can_revert_pago', 'Puede revertir aplicaciones de pago')], 'verbose_name': 'Pagos: 3.Confirmados', 'verbose_name_plural': 'Pagos: 3.Confirmados'},
        ),
        migrations.AddField(
            model_name='fechas_sistema',
            name='ambiente_sistema',
            field=models.CharField(choices=[('PRODUCCION', 'Producción'), ('CAPACITACION', 'Capacitación'), ('PRUEBAS', 'Pruebas')], default='PRUEBAS', help_text='Entorno del sistema: Producción, Capacitación, Pruebas', max_length=12),
        ),
        migrations.AddField(
            model_name='fechas_sistema',
            name='email_entrante',
            field=models.CharField(blank=True, help_text='Cuenta de correo para solicitudes de Financiación', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fechas_sistema',
            name='email_saliente',
            field=models.CharField(blank=True, help_text='Lista de correos para copias de salida', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='inbox_pagosdetalle',
            name='conciliacion_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='inbox_pagosdetalle',
            name='cuota_inicial',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='aseguradora_id',
            field=models.ForeignKey(blank=True, db_column='aseguradora_id', on_delete=django.db.models.deletion.PROTECT, to='appfinancia.aseguradoras'),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='asesor_id',
            field=models.ForeignKey(blank=True, db_column='asesor_id', on_delete=django.db.models.deletion.PROTECT, to='appfinancia.asesores'),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='vendedor_id',
            field=models.ForeignKey(blank=True, db_column='vendedor_id', help_text='Codigo de venta', null=True, on_delete=django.db.models.deletion.PROTECT, to='appfinancia.vendedores'),
        ),
        migrations.AlterField(
            model_name='fechas_sistema',
            name='cambiado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fechas_sistema',
            name='fecha_proceso_actual',
            field=models.DateField(verbose_name='Fecha Proceso Actual'),
        ),
        migrations.AlterField(
            model_name='fechas_sistema',
            name='fecha_proceso_anterior',
            field=models.DateField(verbose_name='Fecha Proceso Anterior'),
        ),
        migrations.AlterField(
            model_name='fechas_sistema',
            name='fecha_proximo_proceso',
            field=models.DateField(verbose_name='Fecha Próximo Proceso'),
        ),
        migrations.AlterField(
            model_name='inbox_pagosdetalle',
            name='clase_movimiento',
            field=models.CharField(blank=True, choices=[('PAGO_PSE', 'Pago PSE'), ('PAGO_BANCOL', 'Pago Bancolombia'), ('LOTE_PSE', 'Lote PSE'), ('EXLUIDO', 'Excluido')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inbox_pagosdetalle',
            name='estado_fragmentacion',
            field=models.CharField(blank=True, choices=[('NO_REQUIERE', 'NO_REQUIERE'), ('A_FRAGMENTAR', 'A_FRAGMENTAR'), ('FRAGMENTADO', 'FRAGMENTADO')], max_length=20),
        ),
        migrations.AlterField(
            model_name='inbox_pagosdetalle',
            name='fecha_pago',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='ref_cliente_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='ref_cliente_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='ref_cliente_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='Financiacion',
            fields=[
                ('solicitud_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('financiacion_id', models.CharField(max_length=10, unique=True)),
                ('email_origen', models.CharField(max_length=100)),
                ('asunto', models.CharField(max_length=200)),
                ('fecha_solicitud', models.DateTimeField()),
                ('nombre_completo', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(max_length=100)),
                ('numero_documento', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('correo_electronico', models.CharField(max_length=100)),
                ('asesor', models.CharField(max_length=100)),
                ('agencia', models.CharField(max_length=100)),
                ('numero_cuotas', models.CharField(max_length=100)),
                ('valor_prestamo', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('valor_cuota_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('valor_seguro_vida', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('tasa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('seguro_vida', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='NO', max_length=2)),
                ('cliente_nuevo', models.CharField(blank=True, max_length=2, null=True)),
                ('cliente_vetado', models.CharField(blank=True, max_length=2, null=True)),
                ('placas', models.CharField(blank=True, max_length=100)),
                ('numero_poliza', models.CharField(blank=True, max_length=100)),
                ('adjunta_cedula', models.FileField(blank=True, null=True, upload_to='financiacion/cedulas/')),
                ('adjunta_poliza', models.FileField(blank=True, null=True, upload_to='financiacion/polizas/')),
                ('adjunta_segurovida', models.FileField(blank=True, null=True, upload_to='financiacion/segurovida/')),
                ('adjunta_archivo_a', models.FileField(blank=True, null=True, upload_to='financiacion/archivo_a/')),
                ('adjunta_archivo_b', models.FileField(blank=True, null=True, upload_to='financiacion/archivo_b/')),
                ('adjunta_archivo_c', models.FileField(blank=True, null=True, upload_to='financiacion/archivo_c/')),
                ('estado_solicitud', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('APROBADO', 'Aprobado'), ('NEGADO', 'Negado')], default='RECIBIDO', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('info_cliente_valida', models.BooleanField(default=False, verbose_name='Información del cliente válida')),
                ('adjunta_documento_identificacion', models.BooleanField(default=False, verbose_name='Adjuntó documento de identificación')),
                ('adjunta_poliza_seguro', models.BooleanField(default=False, verbose_name='Adjuntó póliza de seguro')),
                ('adjunta_autorizacion_datos', models.BooleanField(default=False, verbose_name='Adjuntó autorización de datos personales')),
                ('adjunta_seguro_vida', models.BooleanField(default=False, verbose_name='Adjuntó seguro de vida (opcional)')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financiaciones', to='appfinancia.clientes')),
                ('desembolso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financiaciones', to='appfinancia.desembolsos')),
                ('num_pago_cuota_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financiaciones', to='appfinancia.inbox_pagosdetalle')),
            ],
            options={
                'verbose_name': 'Financiación',
                'verbose_name_plural': 'Financiación',
            },
        ),
        migrations.CreateModel(
            name='Financiacion_PlanPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=150)),
                ('cliente_id', models.CharField(max_length=30)),
                ('poliza', models.CharField(max_length=100)),
                ('aseguradora', models.CharField(max_length=100)),
                ('valor_poliza', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_cuota_0', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_seguro_vida', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tasa_mensual', models.DecimalField(decimal_places=6, max_digits=10)),
                ('plazo_meses', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('financiacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fin_plan_pago', to='appfinancia.financiacion')),
            ],
            options={
                'db_table': 'fin_plan_pago',
            },
        ),
        migrations.CreateModel(
            name='Financiacion_DetallePlanPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.IntegerField()),
                ('valor_cuota', models.DecimalField(decimal_places=2, max_digits=15)),
                ('abono_capital', models.DecimalField(decimal_places=2, max_digits=15)),
                ('intereses', models.DecimalField(decimal_places=2, max_digits=15)),
                ('saldo_capital', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('pagada', models.BooleanField(default=False)),
                ('plan_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fin_detalles', to='appfinancia.financiacion_planpago')),
            ],
            options={
                'db_table': 'fin_detalle_plan_pago',
                'ordering': ['numero_cuota'],
            },
        ),
    ]
