# Generated by Django 5.2.7 on 2025-12-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0054_extractobancario_extractobancariomovimientos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractobancario',
            name='empresa',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='extractobancario',
            name='fecha_hora_actual',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extractobancario',
            name='fecha_hora_consulta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extractobancario',
            name='nit',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='extractobancario',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='extractobancario',
            name='saldo_efectivo_actual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='extractobancario',
            name='saldo_en_canje_actual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='extractobancario',
            name='saldo_total_actual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='extractobancario',
            name='tipo_de_cuenta',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='extractobancariomovimientos',
            name='documento',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='extractobancariomovimientos',
            name='referencia_1',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='extractobancariomovimientos',
            name='referencia_2',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='extractobancariomovimientos',
            name='sucursal_canal',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
