# Generated by Django 5.2.7 on 2025-12-03 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0055_alter_extractobancario_empresa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractobancariomovimientos',
            name='nombre_archivo',
        ),
        migrations.RemoveField(
            model_name='extractobancariomovimientos',
            name='cliente_id_real',
        ),
        migrations.RemoveField(
            model_name='extractobancariomovimientos',
            name='prestamo_id_real',
        ),
        migrations.DeleteModel(
            name='ExtractoBancario',
        ),
        migrations.DeleteModel(
            name='ExtractoBancarioMovimientos',
        ),
    ]
