# Generated by Django 5.2.7 on 2025-12-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0055_alter_fechas_sistema_options_acumulado_interes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acumulado_interes',
            name='prestamo',
        ),
        migrations.AlterModelOptions(
            name='fechas_sistema',
            options={'verbose_name': 'Fecha de Sistema', 'verbose_name_plural': 'Fechas de Sistema'},
        ),
        migrations.AlterUniqueTogether(
            name='historia_prestamos',
            unique_together={('prestamo_id', 'fecha_efectiva', 'ordinal_interno', 'fecha_proceso', 'numero_operacion')},
        ),
        migrations.AddField(
            model_name='historia_prestamos',
            name='capital_aplicado_periodo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto total de capital aplicado en este período', max_digits=15),
        ),
        migrations.AddField(
            model_name='historia_prestamos',
            name='numero_asiento_contable',
            field=models.PositiveIntegerField(default=0, help_text='Número único que identifica el bloque de registros de un mismo pago'),
        ),
        migrations.AddField(
            model_name='historia_prestamos',
            name='numero_pago_referencia',
            field=models.CharField(blank=True, help_text='Referencia del pago que generó este cierre de periodo', max_length=50),
        ),
        migrations.AddIndex(
            model_name='historia_prestamos',
            index=models.Index(fields=['numero_asiento_contable'], name='appfinancia_numero__062496_idx'),
        ),
        migrations.AddIndex(
            model_name='historia_prestamos',
            index=models.Index(fields=['prestamo_id', 'numero_asiento_contable'], name='appfinancia_prestam_ac2a50_idx'),
        ),
        migrations.DeleteModel(
            name='Acumulado_Interes',
        ),
    ]
