# Generated by Django 5.2.7 on 2025-12-03 15:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0056_remove_extractobancariomovimientos_nombre_archivo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractoBancario',
            fields=[
                ('nombre_archivo_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('empresa', models.CharField(max_length=60)),
                ('nit', models.CharField(max_length=16)),
                ('numero_cuenta', models.CharField(max_length=20)),
                ('tipo_cuenta', models.CharField(max_length=20)),
                ('fecha_hora_actual', models.DateTimeField()),
                ('fecha_hora_consulta', models.DateTimeField()),
                ('saldo_efectivo_actual', models.DecimalField(decimal_places=2, max_digits=13)),
                ('saldo_en_canje_actual', models.DecimalField(decimal_places=2, max_digits=13)),
                ('saldo_total_actual', models.DecimalField(decimal_places=2, max_digits=13)),
                ('fecha_carga_archivo', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado_proceso_archivo', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('A_CONCILIAR', 'A Conciliar'), ('ANULADO', 'Anulado')], default='RECIBIDO', max_length=20)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExtractoBancarioMovimientos',
            fields=[
                ('movimiento_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_movimiento', models.DateField()),
                ('descripcion', models.CharField(max_length=120)),
                ('sucursal_canal', models.CharField(blank=True, max_length=60, null=True)),
                ('referencia_1', models.CharField(blank=True, max_length=60, null=True)),
                ('referencia_2', models.CharField(blank=True, max_length=60, null=True)),
                ('documento', models.CharField(blank=True, max_length=60, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estado_movimiento', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('ANULADO', 'Anulado'), ('A_CONCILIAR', 'A Conciliar'), ('CONCILIADO', 'Conciliado')], default='RECIBIDO', max_length=20)),
                ('clase_movimiento', models.CharField(choices=[('PAGO_DIRECTO_CLIENTE', 'Pago Directo Cliente'), ('ABONO_PSE', 'Abono PSE'), ('OTROS', 'Otros')], default='OTROS', max_length=30)),
                ('cliente_id_real', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appfinancia.clientes')),
                ('nombre_archivo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='appfinancia.extractobancario')),
                ('prestamo_id_real', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appfinancia.prestamos')),
            ],
        ),
    ]
