# Generated by Django 5.2.7 on 2025-12-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0056_remove_acumulado_interes_prestamo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultasReportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas y Reportes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CausacionProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Consulta de Causación',
                'verbose_name_plural': 'Consulta de Causación',
                'proxy': True,
                'default_permissions': ('view',),
                'indexes': [],
                'constraints': [],
            },
            bases=('appfinancia.consultasreportes',),
        ),
    ]
