# Generated by Django 5.2.7 on 2025-12-06 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0057_consultasreportes_causacionproxy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultasreportes',
            options={'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas y Reportes'},
        ),
    ]
