# Generated by Django 5.2.7 on 2025-12-03 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0057_extractobancario_extractobancariomovimientos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractoBancolombia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.FileField(upload_to='extractos/bancolombia/')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('nit_bancolombia', models.CharField(blank=True, max_length=20)),
                ('empresa', models.CharField(blank=True, max_length=200)),
                ('nit_empresa', models.CharField(blank=True, max_length=20)),
                ('numero_cuenta', models.CharField(blank=True, max_length=20)),
                ('tipo_cuenta', models.CharField(blank=True, max_length=20)),
                ('fecha_actual', models.DateField(blank=True, null=True)),
                ('fecha_consulta', models.DateField(blank=True, null=True)),
                ('saldo_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('saldo_canje', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('saldo_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoBancolombia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
                ('referencia1', models.CharField(blank=True, max_length=100)),
                ('referencia2', models.CharField(blank=True, max_length=100)),
                ('documento', models.CharField(blank=True, max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=10)),
                ('extracto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='appfinancia.extractobancolombia')),
            ],
            options={
                'ordering': ['-fecha', 'id'],
            },
        ),
    ]
