# Generated by Django 5.2.7 on 2025-12-03 21:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0058_extractobancolombia_movimientobancolombia'),
    ]

    operations = [
        migrations.CreateModel(
            name='grok_Extracto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha del movimiento')),
                ('descripcion', models.CharField(help_text='Descripción del movimiento', max_length=200)),
                ('sucursal_canal', models.CharField(help_text='Sucursal o canal', max_length=100)),
                ('referencia1', models.CharField(blank=True, help_text='Referencia 1', max_length=100)),
                ('referencia2', models.CharField(blank=True, help_text='Referencia 2', max_length=100)),
                ('documento', models.CharField(blank=True, help_text='Documento', max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor del movimiento', max_digits=15)),
                ('fecha_carga', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de carga del extracto')),
                ('archivo_origen', models.FileField(help_text='Archivo PDF original', upload_to='extractos/')),
            ],
            options={
                'verbose_name': 'Movimiento Extracto Bancolombia',
                'verbose_name_plural': 'Movimientos Extracto Bancolombia',
                'ordering': ['-fecha'],
            },
        ),
    ]
