# Generated by Django 5.2.7 on 2025-12-06 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0058_alter_consultasreportes_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='causacionproxy',
            options={'default_permissions': ('view',), 'verbose_name': 'Consulta de Causacion', 'verbose_name_plural': 'Consultas de Causacion'},
        ),
        migrations.AlterModelOptions(
            name='consultasreportes',
            options={'default_permissions': ('view',), 'managed': True, 'verbose_name': 'Consulta Causacion', 'verbose_name_plural': 'Consultas de Causacion'},
        ),
    ]
