# Generated by Django 5.2.7 on 2025-12-07 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0059_alter_causacionproxy_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultasreportes',
            options={'default_permissions': 'view', 'managed': True, 'verbose_name': 'Consulta de Causacion', 'verbose_name_plural': 'Consultas de Causacion'},
        ),
    ]
