# Generated by Django 5.2.7 on 2025-12-03 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0059_grok_extracto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='grok_Extracto',
            new_name='ExtractoBanco',
        ),
    ]
