# Generated by Django 5.2.7 on 2025-12-07 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0060_alter_consultasreportes_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CausacionProxy',
        ),
        migrations.CreateModel(
            name='ConsultasReportesProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Consulta de Causación',
                'verbose_name_plural': 'Consultas y Reportes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('appfinancia.consultasreportes',),
        ),
        migrations.AlterModelOptions(
            name='consultasreportes',
            options={'managed': False, 'permissions': [('puede_consultar_causacion', 'Puede acceder a la consulta de causación')], 'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas y Reportes'},
        ),
    ]
