# Generated by Django 5.2.7 on 2025-12-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0060_rename_grok_extracto_extractobanco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractobanco',
            name='fecha',
            field=models.CharField(blank=True, help_text='Fecha Movimiento', max_length=20, null=True),
        ),
    ]
