# Generated by Django 5.2.7 on 2025-12-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0061_delete_causacionproxy_consultasreportesproxy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Migrados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestamo_id', models.BigIntegerField(help_text='ID del préstamo migrado (coincide con Desembolsos.prestamo_id)')),
                ('origen_migracion', models.CharField(blank=True, help_text="Nombre del archivo Excel de origen (ej. 'aresmig.xlsx')", max_length=100, null=True)),
                ('fecha_migracion', models.DateField(auto_now_add=True, help_text='Fecha en que se realizó la migración')),
                ('hora_migracion', models.DateTimeField(auto_now_add=True, help_text='Hora exacta en que se registró la migración')),
            ],
            options={
                'verbose_name': 'Préstamo Migrado',
                'verbose_name_plural': 'Préstamos Migrados',
                'ordering': ['-fecha_migracion', '-hora_migracion'],
            },
        ),
    ]
