# Generated by Django 5.2.7 on 2025-12-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0061_alter_extractobanco_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractobanco',
            name='documento',
            field=models.CharField(blank=True, help_text='Documento', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extractobanco',
            name='referencia1',
            field=models.CharField(blank=True, help_text='Referencia 1', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extractobanco',
            name='referencia2',
            field=models.CharField(blank=True, help_text='Referencia 2', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extractobanco',
            name='sucursal_canal',
            field=models.CharField(help_text='Sucursal o canal', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extractobanco',
            name='valor',
            field=models.DecimalField(decimal_places=2, help_text='Valor del movimiento', max_digits=15, null=True),
        ),
    ]
