# Generated by Django 5.2.7 on 2025-12-10 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0062_migrados'),
    ]

    operations = [
        #migrations.RemoveField(
        #    model_name='extractobancariomovimientos',
        #    name='nombre_archivo',
        #),
        #migrations.RemoveField(
        #    model_name='extractobancariomovimientos',
        #    name='cliente_id_real',
        #),
        #migrations.RemoveField(
        #    model_name='extractobancariomovimientos',
         #   name='prestamo_id_real',
        #),
        migrations.AlterField(
            model_name='clientes',
            name='tipo_id',
            field=models.ForeignKey(help_text='Tipo de identificación (ej. CC, TI, CE, PA, NIT).', on_delete=django.db.models.deletion.PROTECT, to='appfinancia.tipos_identificacion'),
        ),
        #migrations.DeleteModel(
        #    name='ExtractoBancario',
        #),
        #migrations.DeleteModel(
        #    name='ExtractoBancarioMovimientos',
        #),
    ]
