# Generated by Django 5.2.7 on 2025-12-05 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0062_alter_extractobanco_documento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extractobanco',
            options={'ordering': ['-fecha'], 'verbose_name': 'Cargar Extracto Bancolombia', 'verbose_name_plural': 'Cargar Extracto Bancolombia'},
        ),
    ]
