# Generated by Django 5.2.7 on 2025-12-10 21:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0063_remove_extractobancariomovimientos_nombre_archivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='direccion',
            field=models.CharField(help_text='Dirección del cliente (máximo 120 caracteres).', max_length=120),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(help_text='Correo electrónico del cliente (máximo 120 caracteres).', max_length=120, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
