# Generated by Django 5.2.7 on 2025-12-05 05:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0063_alter_extractobanco_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BancolombiaExtracto',
            fields=[
                ('nombre_archivo_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('empresa', models.CharField(blank=True, max_length=60, null=True)),
                ('nit', models.CharField(blank=True, max_length=16, null=True)),
                ('numero_cuenta', models.CharField(blank=True, max_length=12, null=True)),
                ('tipo_cuenta', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_hora_actual', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_hora_consulta', models.CharField(blank=True, max_length=20, null=True)),
                ('saldo_efectivo_actual', models.CharField(blank=True, max_length=20, null=True)),
                ('saldo_en_canje_actual', models.CharField(blank=True, max_length=20, null=True)),
                ('saldo_total_actual', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_carga_archivo', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('estado_del_archivo', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('A_CONCILIAR', 'A Conciliar'), ('ANULADO', 'Anulado')], default='RECIBIDO', max_length=15)),
                ('registro_extracto', models.CharField(blank=True, max_length=200, null=True)),
                ('creado_por', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BancolombiaMovimientos',
            fields=[
                ('movimiento_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_movimiento', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=70, null=True)),
                ('sucursal_canal', models.CharField(blank=True, max_length=20, null=True)),
                ('referencia_1', models.CharField(blank=True, max_length=20, null=True)),
                ('referencia_2', models.CharField(blank=True, max_length=20, null=True)),
                ('documento', models.CharField(blank=True, max_length=20, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('estado_movimiento', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('ANULADO', 'Anulado'), ('A_CONCILIAR', 'A Conciliar'), ('CONCILIADO', 'Conciliado')], default='RECIBIDO', max_length=15)),
                ('clase_movimiento', models.CharField(blank=True, choices=[('PAGO_DIRECTO_CLIENTE', 'Pago Directo Cliente'), ('ABONO_PSE', 'Abono PSE'), ('OTROS', 'Otros')], max_length=30, null=True)),
                ('registro_extracto', models.CharField(blank=True, max_length=150, null=True)),
                ('cliente_id_real', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appfinancia.clientes')),
                ('nombre_archivo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appfinancia.bancolombiaextracto')),
                ('prestamo_id_real', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appfinancia.prestamos')),
            ],
        ),
    ]
