# Generated by Django 5.2.7 on 2025-12-05 05:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0064_bancolombiaextracto_bancolombiamovimientos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancolombiaextracto',
            name='fecha_carga_archivo',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True),
        ),
    ]
