# Generated by Django 5.2.7 on 2025-12-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0064_clientes_observaciones_alter_clientes_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='nombre_archivo_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.DeleteModel(
            name='Pagos_Archivos',
        ),
    ]
