# Generated by Django 5.2.7 on 2025-12-11 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0065_alter_pagos_nombre_archivo_id_delete_pagos_archivos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagos',
            name='valor_aplicado_acreedores',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='valor_aplicado_capital',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='valor_aplicado_gastos',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='valor_aplicado_intereses',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='valor_aplicado_otros',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='valor_aplicado_seguros',
        ),
    ]
