# Generated by Django 5.2.7 on 2025-12-05 06:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0065_alter_bancolombiaextracto_fecha_carga_archivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancolombiaextracto',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bancolombiaextracto',
            name='fecha_carga_archivo',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='bancolombiaextracto',
            name='fecha_hora_actual',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bancolombiaextracto',
            name='fecha_hora_consulta',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bancolombiaextracto',
            name='saldo_efectivo_actual',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bancolombiaextracto',
            name='saldo_en_canje_actual',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bancolombiaextracto',
            name='saldo_total_actual',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bancolombiaextracto',
            name='tipo_cuenta',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
