# Generated by Django 5.2.7 on 2025-12-05 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0066_alter_bancolombiaextracto_creado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancolombiaextracto',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bancolombiaextracto',
            name='estado_del_archivo',
            field=models.CharField(blank=True, choices=[('RECIBIDO', 'Recibido'), ('A_CONCILIAR', 'A Conciliar'), ('ANULADO', 'Anulado')], max_length=15, null=True),
        ),
    ]
