# Generated by Django 5.2.7 on 2025-12-06 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0067_alter_bancolombiaextracto_creado_por_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractobancario',
            name='creado_por',
        ),
        #migrations.RemoveField(
        #    model_name='extractobancariomovimientos',
        #    name='nombre_archivo_id',
        #),
        #migrations.RemoveField(
        #    model_name='extractobancariomovimientos',
        #    name='cliente_id_real',
        #),
        #migrations.RemoveField(
        #    model_name='extractobancariomovimientos',
        #    name='prestamo_id_real',
        #),
        #migrations.DeleteModel(
        #    name='ExtractoBanco',
        #),
        #migrations.RemoveField(
        #    model_name='extractobancolombia',
        #    name='usuario',
        #),
        migrations.RemoveField(
            model_name='movimientobancolombia',
            name='extracto',
        ),
        #migrations.DeleteModel(
        #    name='ExtractoBancario',
        #),
        #migrations.DeleteModel(
        #    name='ExtractoBancarioMovimientos',
        #),
        #migrations.DeleteModel(
        #    name='ExtractoBancolombia',
        #),
        migrations.DeleteModel(
            name='MovimientoBancolombia',
        ),
    ]
