# Generated by Django 5.2.7 on 2025-12-09 11:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0068_remove_extractobancario_creado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InBox_PagosCabezal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('formato', models.CharField(choices=[('1-FORMATO PSE', '1 - Formato PSE'), ('2-FORMATO ESTANDAR', '2 - Formato Estándar'), ('3-FORMATO EXTRACTO BANCOLOMBIA', '3 - Extracto Bancolombia')], max_length=30)),
                ('fecha_carga_archivo', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('banco_origen', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('registros_cargados', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('registros_rechazados', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('estado_proceso_archivo', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('A_PROCESAR', 'A_PROCESAR'), ('ANULADO', 'Anulado')], default='RECIBIDO', max_length=10)),
                ('observaciones', models.CharField(blank=True, max_length=200)),
                ('creado_por', models.ForeignKey(blank=True, editable=False, help_text='Usuario que registró el comentario.', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'InBox Archivo de Pagos',
                'verbose_name_plural': 'InBox Archivos de Pagos',
                'ordering': ['-fecha_carga_archivo'],
            },
        ),
        migrations.CreateModel(
            name='InBox_PagosDetalle',
            fields=[
                ('pago_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('grupo_pse_id', models.BigIntegerField(blank=True, null=True)),
                ('fragmento_de', models.BigIntegerField(blank=True, null=True)),
                ('fecha_carga_archivo', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('banco_origen', models.CharField(blank=True, max_length=100)),
                ('cuenta_bancaria', models.CharField(blank=True, max_length=100)),
                ('tipo_cuenta_bancaria', models.CharField(blank=True, choices=[('AHORROS', 'Ahorros'), ('CORRIENTE', 'Corriente')], max_length=9)),
                ('canal_red_pago', models.CharField(blank=True, max_length=100)),
                ('ref_bancaria', models.CharField(blank=True, max_length=100)),
                ('ref_red', models.CharField(blank=True, max_length=100)),
                ('ref_cliente_1', models.CharField(blank=True, max_length=200)),
                ('ref_cliente_2', models.CharField(blank=True, max_length=200)),
                ('ref_cliente_3', models.CharField(blank=True, max_length=200)),
                ('estado_transaccion_reportado', models.CharField(blank=True, max_length=20)),
                ('clase_movimiento', models.CharField(blank=True, choices=[('1-PAGO_DIRECTO_CLIENTE', 'Pago Directo Cliente'), ('2-PAGO_EN_GRUPO_PSE', 'Abono PSE'), ('3-OTROS', 'Otros')], max_length=30, null=True)),
                ('estado_fragmentacion', models.CharField(blank=True, choices=[('NO_REQUIERE', 'No requiere'), ('A_FRAMENTAR', 'A fragmentar'), ('FRAGMENTADO', 'Fragmentado')], max_length=20)),
                ('cliente_id_reportado', models.CharField(blank=True, max_length=20)),
                ('prestamo_id_reportado', models.CharField(blank=True, max_length=20)),
                ('poliza_id_reportado', models.CharField(blank=True, max_length=20)),
                ('poliza_id_real', models.CharField(blank=True, max_length=20)),
                ('fecha_pago', models.DateField()),
                ('fecha_conciliacion', models.DateTimeField(blank=True, null=True)),
                ('estado_pago', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('A_PROCESAR', 'A_PROCESAR'), ('ANULADO', 'Anulado'), ('CONCILIADO', 'Conciliado')], max_length=12, null=True)),
                ('estado_conciliacion', models.CharField(blank=True, choices=[('cliente o prestamo no existe', 'Cliente o préstamo no existe'), ('prestamo_cancelado', 'Préstamo cancelado')], max_length=30, null=True)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('observaciones', models.CharField(blank=True, max_length=200)),
                ('cliente_id_real', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appfinancia.clientes')),
                ('creado_por', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('nombre_archivo_id', models.ForeignKey(help_text='Archivo de origen', on_delete=django.db.models.deletion.PROTECT, to='appfinancia.inbox_pagoscabezal', to_field='nombre_archivo_id')),
                ('prestamo_id_real', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appfinancia.prestamos')),
            ],
            options={
                'verbose_name': 'InBoxPago',
                'verbose_name_plural': 'InBoxPagos',
            },
        ),
    ]
