# Generated by Django 5.2.7 on 2025-12-09 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0069_inbox_pagoscabezal_inbox_pagosdetalle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox_pagoscabezal',
            name='archivo',
            field=models.FileField(blank=True, help_text='Seleccione el archivo a cargar', null=True, upload_to='pagos_archivos/'),
        ),
        migrations.AlterField(
            model_name='inbox_pagoscabezal',
            name='creado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inbox_pagoscabezal',
            name='estado_proceso_archivo',
            field=models.CharField(choices=[('RECIBIDO', 'Recibido'), ('A_PROCESAR', 'A_PROCESAR'), ('ANULADO', 'Anulado')], default='RECIBIDO', max_length=20),
        ),
    ]
