# Generated by Django 5.2.7 on 2025-12-10 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0070_inbox_pagoscabezal_archivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fragmentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bancolombiamovimientos',
            name='nombre_archivo_id',
        ),
        migrations.RemoveField(
            model_name='bancolombiamovimientos',
            name='cliente_id_real',
        ),
        migrations.RemoveField(
            model_name='bancolombiamovimientos',
            name='prestamo_id_real',
        ),
        migrations.AlterModelOptions(
            name='inbox_pagoscabezal',
            options={'ordering': ['-fecha_carga_archivo'], 'verbose_name': 'InBox Pagos', 'verbose_name_plural': 'InBox Pagos'},
        ),
        migrations.AlterModelOptions(
            name='inbox_pagosdetalle',
            options={'verbose_name': 'InBox Pago Recibido', 'verbose_name_plural': 'InBox Pagos Recibidos'},
        ),
        migrations.AlterField(
            model_name='inbox_pagoscabezal',
            name='estado_proceso_archivo',
            field=models.CharField(choices=[('RECIBIDO', 'Recibido'), ('A_PROCESAR', 'A procesar'), ('ANULADO', 'Anulado')], default='RECIBIDO', max_length=20),
        ),
        migrations.AlterField(
            model_name='inbox_pagosdetalle',
            name='estado_pago',
            field=models.CharField(choices=[('RECIBIDO', 'Recibido'), ('A_PROCESAR', 'A procesar'), ('ANULADO', 'Anulado'), ('CONCILIADO', 'Conciliado')], max_length=12, null=True),
        ),
        migrations.CreateModel(
            name='FragmentacionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField()),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('fragmentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='appfinancia.fragmentacion')),
            ],
        ),
        migrations.DeleteModel(
            name='BancolombiaExtracto',
        ),
        migrations.DeleteModel(
            name='BancolombiaMovimientos',
        ),
    ]
