# Generated by Django 5.2.7 on 2025-12-10 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0071_fragmentacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fragmentaciondetalle',
            name='fragmentacion',
        ),
        migrations.DeleteModel(
            name='Fragmentacion',
        ),
        migrations.DeleteModel(
            name='FragmentacionDetalle',
        ),
    ]
