# Generated by Django 5.2.7 on 2025-12-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0072_remove_fragmentaciondetalle_fragmentacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FragmentacionMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Fragmentación',
                'verbose_name_plural': 'Fragmentación',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='inbox_pagosdetalle',
            name='clase_movimiento',
            field=models.CharField(blank=True, choices=[('1-PAGO_DIRECTO', 'Pago Directo Cliente'), ('2-PAGO_EN_GRUPO_PSE', 'Abono PSE'), ('3-NO_ES_UN_PAGO', 'No es un pago a prestamos')], max_length=30, null=True),
        ),
    ]
