# Generated by Django 5.2.7 on 2025-12-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0073_fragmentacionmenu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox_pagosdetalle',
            name='clase_movimiento',
            field=models.CharField(blank=True, choices=[('1_PAGO_DIRECTO', 'Pago Directo Cliente'), ('2_PAGO_EN_GRUPO_PSE', 'Abono PSE'), ('3_NO_ES_UN_PAGO', 'No es un pago a prestamos')], max_length=30, null=True),
        ),
    ]
