# Generated by Django 5.2.7 on 2025-12-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0074_alter_inbox_pagosdetalle_clase_movimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox_pagosdetalle',
            name='clase_movimiento',
            field=models.CharField(blank=True, choices=[('PAGO_DIRECTO', 'Pago Directo Cliente'), ('PAGO_EN_GRUPO_PSE', 'Abono PSE'), ('NO_ES_UN_PAGO', 'No es un pago a prestamos')], max_length=30, null=True),
        ),
    ]
