# Generated by Django 5.2.7 on 2025-12-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0075_alter_inbox_pagosdetalle_clase_movimiento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FragmentacionMenu',
        ),
        migrations.AlterField(
            model_name='inbox_pagosdetalle',
            name='clase_movimiento',
            field=models.CharField(blank=True, choices=[('PAGO_DIRECTO', 'Pago Directo'), ('PAGO_EN_GRUPO', 'Abono PSE'), ('NO_ES_UN_PAGO', 'No es un pago')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inbox_pagosdetalle',
            name='estado_pago',
            field=models.CharField(choices=[('RECIBIDO', 'Recibido'), ('A_PROCESAR', 'A procesar'), ('ANULADO', 'Anulado'), ('CONCILIADO', 'Conciliado'), ('A_REGULARIZAR', 'A regularizar')], max_length=20, null=True),
        ),
    ]
