# Generated by Django 5.2.7 on 2025-12-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0076_delete_fragmentacionmenu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox_pagosdetalle',
            name='clase_movimiento',
            field=models.CharField(blank=True, choices=[('PAGO_DIRECTO', 'Pago Directo'), ('PAGO_EN_GRUPO_PSE', 'Abono PSE'), ('NO_ES_UN_PAGO', 'No es un pago')], max_length=30, null=True),
        ),
    ]
