# Generated by Django 5.2.7 on 2025-12-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0077_alter_inbox_pagosdetalle_clase_movimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagos',
            name='valor_aplicado_acreedores',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='valor_aplicado_capital',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='valor_aplicado_gastos',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='valor_aplicado_intereses',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='valor_aplicado_otros',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='valor_aplicado_seguros',
        ),
        #migrations.AlterField(
        #    model_name='pagos',
        #    name='nombre_archivo_id',
        #    field=models.CharField(db_index=True, help_text='Identificador del archivo de origen (no es ForeignKey)', max_length=200),
        #),
    ]
