# Generated by Django 5.2.7 on 2025-12-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0078_remove_pagos_valor_aplicado_acreedores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='nombre_archivo_id',
            field=models.CharField(db_index=True, help_text='Identificador del archivo de origen (no es ForeignKey)', max_length=200),
        ),
        #migrations.DeleteModel(
        #    name='Pagos_Archivos',
        #),
    ]
