# Generated by Django 5.2.7 on 2025-12-12 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0079_alter_pagos_nombre_archivo_id_delete_pagos_archivos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inbox_pagosdetalle',
            old_name='grupo_pse_id',
            new_name='lote_pse',
        ),
    ]
