# Generated by Django 5.2.7 on 2025-12-14 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0080_rename_grupo_pse_id_inbox_pagosdetalle_lote_pse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox_pagosdetalle',
            name='clase_movimiento',
            field=models.CharField(blank=True, choices=[('PAGO_PSE', 'Pago PSE'), ('PAGO_BANCOL', 'Pago Bancolombia'), ('ABONO_PSE', 'Abono PSE'), ('REG_EXCLUIDO', 'Excludio')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inbox_pagosdetalle',
            name='estado_conciliacion',
            field=models.CharField(blank=True, choices=[('CONCILIADO', 'Conciliado'), ('NO_CONCILIADO', 'No Conciliado')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inbox_pagosdetalle',
            name='estado_pago',
            field=models.CharField(choices=[('RECIBIDO', 'Recibido'), ('A_PROCESAR', 'A procesar'), ('ANULADO', 'Anulado'), ('CONFIRMADO', 'Confirmado'), ('A_REGULARIZAR', 'A regularizar')], max_length=20, null=True),
        ),
    ]
