# Generated by Django 5.2.7 on 2025-12-14 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0081_alter_inbox_pagosdetalle_clase_movimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox_pagosdetalle',
            name='clase_movimiento',
            field=models.CharField(blank=True, choices=[('PAGO_PSE', 'Pago PSE'), ('PAGO_BANCOL', 'Pago Bancolombia'), ('ABONO_PSE', 'Abono PSE'), ('EXLUIDO', 'Excludio')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inbox_pagosdetalle',
            name='estado_pago',
            field=models.CharField(choices=[('RECIBIDO', 'Recibido'), ('A_PROCESAR', 'A procesar'), ('ANULADO', 'Anulado'), ('CONFIRMADO', 'Confirmado'), ('A_NORMALIZAR', 'A regularizar'), ('EXCLUIDO', 'Excludio')], max_length=20, null=True),
        ),
    ]
