# Generated by Django 5.2.7 on 2025-12-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0082_alter_inbox_pagosdetalle_clase_movimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox_pagosdetalle',
            name='estado_conciliacion',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True),
        ),
    ]
