# Generated by Django 5.2.7 on 2025-12-16 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0045_pagos_archivos_pagos'),
        ('appfinancia', '0052_alter_pagos_archivos_creado_por'),
        ('appfinancia', '0066_remove_pagos_valor_aplicado_acreedores_and_more'),
        ('appfinancia', '0083_alter_inbox_pagosdetalle_estado_conciliacion'),
    ]

    operations = [
    ]
