# Generated by Django 5.2.7 on 2025-12-18 17:11

import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0084_merge_20251215_2156'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractobancariomovimientos',
            name='nombre_archivo_id',
        ),
        migrations.RemoveField(
            model_name='extractobancariomovimientos',
            name='cliente_id_real',
        ),
        migrations.RemoveField(
            model_name='extractobancariomovimientos',
            name='prestamo_id_real',
        ),
        migrations.DeleteModel(
            name='ExtractoBanco',
        ),
        migrations.RemoveField(
            model_name='extractobancolombia',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='pagos_archivos',
            name='creado_por',
        ),
        migrations.AlterField(
            model_name='pagos',
            name='nombre_archivo_id',
            field=models.CharField(db_index=True, help_text='Identificador del archivo de origen (no es ForeignKey)', max_length=210),
        ),
        migrations.AlterModelOptions(
            name='inbox_pagoscabezal',
            options={'ordering': ['-fecha_carga_archivo'], 'verbose_name': 'InBox archivos de Pagos', 'verbose_name_plural': 'InBox archivos de Pagos'},
        ),
        migrations.AlterModelOptions(
            name='inbox_pagosdetalle',
            options={'verbose_name': 'InBox detalle de pagos', 'verbose_name_plural': 'InBox detalle de pagos'},
        ),
        migrations.AlterModelOptions(
            name='pagos',
            options={'verbose_name': 'Pagos confirmados', 'verbose_name_plural': 'Pagos confirmados'},
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='valor_aplicado_acreedores',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='valor_aplicado_capital',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='valor_aplicado_gastos',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='valor_aplicado_intereses',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='valor_aplicado_otros',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='valor_aplicado_seguros',
        ),
        migrations.AlterField(
            model_name='clientes',
            name='municipio',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='departamento', chained_model_field='departamento', help_text='Municipio del cliente. Debe pertenecer al departamento seleccionado.', on_delete=django.db.models.deletion.CASCADE, to='appfinancia.municipios'),
        ),
        migrations.AlterField(
            model_name='inbox_pagosdetalle',
            name='clase_movimiento',
            field=models.CharField(blank=True, choices=[('PAGO_PSE', 'Pago PSE'), ('PAGO_BANCOL', 'Pago Bancolombia'), ('LOTE_PSE', 'Lote PSE'), ('EXLUIDO', 'Excludio')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='banco_origen',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='canal_red_pago',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='cliente_id_real',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='cliente_id_reportado',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='creado_por',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='cuenta_bancaria',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='estado_conciliacion',
            field=models.CharField(blank=True, choices=[('cliente o prestamo no existe', 'Cliente o préstamo no existe'), ('prestamo_cancelado', 'Préstamo cancelado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='estado_pago',
            field=models.CharField(choices=[('Recibido', 'Recibido'), ('pendiente', 'Pendiente'), ('rechazado', 'Rechazado'), ('conciliado', 'Conciliado'), ('aplicado', 'Aplicado'), ('reversado', 'Reversado')], default='Recibido', max_length=12),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='estado_transaccion_reportado',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='fecha_aplicacion_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='fecha_carga_archivo',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='fecha_conciliacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='fecha_pago',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='hora_pago',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='pago_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='poliza_id_real',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='poliza_id_reportado',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='prestamo_id_real',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='prestamo_id_reportado',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='ref_bancaria',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='ref_cliente_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='ref_cliente_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='ref_cliente_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='ref_red',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='tipo_cuenta_bancaria',
            field=models.CharField(blank=True, choices=[('AHORROS', 'Ahorros'), ('CORRIENTE', 'Corriente')], max_length=9),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.DeleteModel(
            name='ExtractoBancario',
        ),
        migrations.DeleteModel(
            name='ExtractoBancarioMovimientos',
        ),
        migrations.DeleteModel(
            name='ExtractoBancolombia',
        ),
        migrations.DeleteModel(
            name='Pagos_Archivos',
        ),
    ]
