# Generated by Django 5.2.7 on 2025-12-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0085_remove_extractobancariomovimientos_nombre_archivo_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_aplicacion_pago',
            name='pago',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='nombre_archivo_id',
            field=models.CharField(db_index=True, help_text='Identificador del archivo de origen (no es ForeignKey)', max_length=200),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='pago_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
