# Generated by Django 5.2.7 on 2025-12-18 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0086_alter_detalle_aplicacion_pago_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_aplicacion_pago',
            name='pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_aplicacion', to='appfinancia.pagos'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='estado_pago',
            field=models.CharField(choices=[('CONCILIADO', 'Conciliado'), ('APLICADO', 'Aplicado'), ('REVERSADO', 'Reversado')], default='Recibido', max_length=12),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='pago_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
