# Generated by Django 5.2.7 on 2025-12-19 20:41

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0087_alter_detalle_aplicacion_pago_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox_pagosdetalle',
            name='prestamo_id_real',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='cliente_id_real', chained_model_field='prestamo_id', help_text='Préstamos del cliente asignado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='appfinancia.prestamos'),
        ),
    ]
