# Generated by Django 5.2.7 on 2025-12-20 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0089_alter_inbox_pagosdetalle_prestamo_id_real'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagosCuotaInicial',
            fields=[
            ],
            options={
                'verbose_name': 'InBox Pago para Regularizar',
                'verbose_name_plural': 'InBox Pagos para Regularizar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('appfinancia.inbox_pagosdetalle',),
        ),
        migrations.CreateModel(
            name='PagosParaRegularizar',
            fields=[
            ],
            options={
                'verbose_name': 'InBox Pago para Regularizar',
                'verbose_name_plural': 'InBox Pagos para Regularizar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('appfinancia.inbox_pagosdetalle',),
        ),
    ]
