# Generated by Django 5.2.7 on 2025-12-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0091_alter_inbox_pagosdetalle_prestamo_id_real'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox_pagosdetalle',
            name='estado_fragmentacion',
            field=models.CharField(blank=True, choices=[('NO_REQUIERE', 'NO_REQUIERE'), ('A_FRAGMENTAR', 'A_FRAGMENTAR'), ('FRAGMENTADO', 'FRAGMENTADO')], max_length=20),
        ),
    ]
