# Generated by Django 5.2.7 on 2025-12-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0092_alter_inbox_pagosdetalle_estado_fragmentacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financiacion',
            fields=[
                ('solicitud_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('financiacion_id', models.CharField(max_length=10, unique=True)),
                ('email_origen', models.CharField(max_length=100)),
                ('asunto', models.CharField(max_length=200)),
                ('fecha_solicitud', models.DateTimeField()),
                ('nombre_completo', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(max_length=100)),
                ('numero_documento', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('correo_electronico', models.CharField(max_length=100)),
                ('asesor', models.CharField(max_length=100)),
                ('agencia', models.CharField(max_length=100)),
                ('numero_cuotas', models.CharField(max_length=100)),
                ('valor_prestamo', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('valor_cuota_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('tasa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('seguro_vida', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='NO', max_length=2)),
                ('cliente_nuevo', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2)),
                ('cliente_vetado', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='NO', max_length=2)),
                ('placas', models.CharField(blank=True, max_length=100)),
                ('numero_poliza', models.CharField(blank=True, max_length=100)),
                ('adjunta_cedula', models.FileField(blank=True, null=True, upload_to='financiacion/cedulas/')),
                ('adjunta_poliza', models.FileField(blank=True, null=True, upload_to='financiacion/polizas/')),
                ('adjunta_segurovida', models.FileField(blank=True, null=True, upload_to='financiacion/segurovida/')),
                ('estado_solicitud', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('APROBADO', 'Aprobado'), ('NEGADO', 'Negado')], default='RECIBIDO', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Solicitud de financiación',
                'verbose_name_plural': 'Solicitudes de financiación',
            },
        ),
    ]
