# Generated by Django 5.2.7 on 2025-12-26 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0093_financiacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fechas_sistema',
            options={'verbose_name': 'Fecha de Sistema', 'verbose_name_plural': 'Fecha de Sistema'},
        ),
        migrations.AlterField(
            model_name='fechas_sistema',
            name='cambiado_por',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fechas_sistema',
            name='estado_sistema',
            field=models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=8),
        ),
        migrations.AlterField(
            model_name='fechas_sistema',
            name='fecha_proceso_actual',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fechas_sistema',
            name='fecha_proceso_anterior',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fechas_sistema',
            name='fecha_proximo_proceso',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fechas_sistema',
            name='fecha_ultima_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fechas_sistema',
            name='modo_fecha_sistema',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATICO', 'Automático')], default='AUTOMATICO', max_length=10),
        ),
    ]
