# Generated by Django 5.2.7 on 2025-12-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0094_alter_fechas_sistema_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financiacion',
            name='adjunta_autorizacion_datos',
            field=models.BooleanField(default=False, verbose_name='Adjuntó autorización de datos personales'),
        ),
        migrations.AddField(
            model_name='financiacion',
            name='adjunta_documento_identificacion',
            field=models.BooleanField(default=False, verbose_name='Adjuntó documento de identificación'),
        ),
        migrations.AddField(
            model_name='financiacion',
            name='adjunta_poliza_seguro',
            field=models.BooleanField(default=False, verbose_name='Adjuntó póliza de seguro'),
        ),
        migrations.AddField(
            model_name='financiacion',
            name='adjunta_seguro_vida',
            field=models.BooleanField(default=False, verbose_name='Adjuntó seguro de vida (opcional)'),
        ),
        migrations.AddField(
            model_name='financiacion',
            name='info_cliente_valida',
            field=models.BooleanField(default=False, verbose_name='Información del cliente válida'),
        ),
    ]
