# Generated by Django 5.2.7 on 2025-12-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0095_financiacion_adjunta_autorizacion_datos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financiacion',
            name='cliente_nuevo',
            field=models.BooleanField(default=False, verbose_name='El cliente es nuevo'),
        ),
        migrations.AlterField(
            model_name='financiacion',
            name='cliente_vetado',
            field=models.BooleanField(default=False, verbose_name='El cliente está vetado'),
        ),
    ]
