# Generated by Django 5.2.7 on 2025-12-31 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0096_alter_financiacion_cliente_nuevo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financiacion_PlanPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=150)),
                ('cliente_id', models.CharField(max_length=30)),
                ('poliza', models.CharField(max_length=100)),
                ('aseguradora', models.CharField(max_length=100)),
                ('valor_poliza', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_cuota_0', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_seguro_vida', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tasa_mensual', models.DecimalField(decimal_places=6, max_digits=10)),
                ('plazo_meses', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('financiacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financiacion_plan_pago', to='appfinancia.financiacion')),
            ],
            options={
                'db_table': 'financiacion_plan_pago',
            },
        ),
        migrations.CreateModel(
            name='Financiacion_DetallePlanPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.IntegerField()),
                ('valor_cuota', models.DecimalField(decimal_places=2, max_digits=15)),
                ('abono_capital', models.DecimalField(decimal_places=2, max_digits=15)),
                ('intereses', models.DecimalField(decimal_places=2, max_digits=15)),
                ('saldo_capital', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('pagada', models.BooleanField(default=False)),
                ('plan_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='appfinancia.financiacion_planpago')),
            ],
            options={
                'db_table': 'financiacion_detalle_plan_pago',
                'ordering': ['numero_cuota'],
            },
        ),
    ]
