# Generated by Django 5.2.7 on 2025-12-31 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0097_financiacion_planpago_financiacion_detalleplanpago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financiacion_detalleplanpago',
            name='plan_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fin_detalles', to='appfinancia.financiacion_planpago'),
        ),
        migrations.AlterField(
            model_name='financiacion_planpago',
            name='financiacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fin_plan_pago', to='appfinancia.financiacion'),
        ),
        migrations.AlterModelTable(
            name='financiacion_detalleplanpago',
            table='fin_detalle_plan_pago',
        ),
        migrations.AlterModelTable(
            name='financiacion_planpago',
            table='fin_plan_pago',
        ),
    ]
