# Generated by Django 5.2.7 on 2026-01-02 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0098_alter_financiacion_detalleplanpago_plan_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financiacion',
            name='valor_seguro_vida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
    ]
