# Generated by Django 5.2.7 on 2026-01-02 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0099_financiacion_valor_seguro_vida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financiacion',
            name='cliente_nuevo',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='financiacion',
            name='cliente_vetado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
