# Generated by Django 5.2.7 on 2026-01-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0100_alter_financiacion_cliente_nuevo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inbox_pagoscabezal',
            options={'ordering': ['-fecha_carga_archivo'], 'verbose_name': 'Pagos: 1.Inbox de Archivos', 'verbose_name_plural': 'Pagos: 1.Inbox de Archivos'},
        ),
        migrations.AlterModelOptions(
            name='inbox_pagosdetalle',
            options={'verbose_name': 'Pagos: 4.Consultas', 'verbose_name_plural': 'Pagos: 4.Consultas'},
        ),
        migrations.AlterModelOptions(
            name='pagos',
            options={'verbose_name': 'Pagos: 3.Confirmados', 'verbose_name_plural': 'Pagos: 3.Confirmados'},
        ),
        migrations.AlterModelOptions(
            name='pagospararegularizar',
            options={'verbose_name': 'Pagos: 2.Conciliación', 'verbose_name_plural': 'Pagos: 2.Conciliación'},
        ),
        migrations.AlterField(
            model_name='inbox_pagosdetalle',
            name='clase_movimiento',
            field=models.CharField(blank=True, choices=[('PAGO_PSE', 'Pago PSE'), ('PAGO_BANCOL', 'Pago Bancolombia'), ('LOTE_PSE', 'Lote PSE'), ('EXLUIDO', 'Excluido')], max_length=30, null=True),
        ),
    ]
