# Generated by Django 5.2.7 on 2026-01-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0101_alter_inbox_pagoscabezal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox_pagosdetalle',
            name='conciliacion_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
