# Generated by Django 5.2.7 on 2026-01-09 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0102_inbox_pagosdetalle_conciliacion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox_pagosdetalle',
            name='fecha_pago',
            field=models.DateTimeField(),
        ),
    ]
