# Generated by Django 5.2.7 on 2026-01-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0103_alter_inbox_pagosdetalle_fecha_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox_pagosdetalle',
            name='conciliacion_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
