# Generated by Django 5.2.7 on 2026-01-11 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0104_alter_inbox_pagosdetalle_conciliacion_id'),
    ]

    operations = [
        #migrations.RemoveField(
        #    model_name='desembolsos',
        #    name='aseguradora_id',
        #),
        #migrations.RemoveField(
        #    model_name='desembolsos',
        #    name='asesor_id',
        #),
        #migrations.RemoveField(
        #    model_name='desembolsos',
        #    name='vendedor_id',
        #),
        #migrations.RemoveField(
        #    model_name='prestamos',
        #    name='aseguradora_id',
        #),
        #migrations.RemoveField(
        #    model_name='prestamos',
        #    name='asesor_id',
        #),
        #migrations.RemoveField(
        #    model_name='prestamos',
        #    name='vendedor_id',
        #),
        #migrations.AddField(
        #    model_name='desembolsos',
        #    name='aseguradora',
        #    field=models.ForeignKey(blank=True, db_column='aseguradora_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='appfinancia.aseguradoras'),
        #),
        #migrations.AddField(
        #    model_name='desembolsos',
        #    name='asesor',
        #    field=models.ForeignKey(blank=True, db_column='asesor_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='appfinancia.asesores'),
        #),
        #migrations.AddField(
        #    model_name='desembolsos',
        #    name='vendedor',
        #    field=models.ForeignKey(blank=True, db_column='vendedor_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='appfinancia.vendedores'),
        #),
        #migrations.AddField(
        #    model_name='prestamos',
        #    name='aseguradora',
        #    field=models.ForeignKey(blank=True, db_column='aseguradora_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='appfinancia.aseguradoras'),
        #),
        #migrations.AddField(
        #    model_name='prestamos',
        #    name='asesor',
        #    field=models.ForeignKey(blank=True, db_column='asesor_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='appfinancia.asesores'),
        #),
        #migrations.AddField(
        #    model_name='prestamos',
        #    name='vendedor',
        #    field=models.ForeignKey(blank=True, db_column='vendedor_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='appfinancia.vendedores'),
        #),
        #migrations.AlterField(
        #    model_name='desembolsos',
        #    name='tipo_tasa',
        #    field=models.ForeignKey(blank=True, db_column='tipo_tasa', help_text="Tipo de tasa (ej. 'CON SEGURO').", null=True, on_delete=django.db.models.deletion.PROTECT, to='appfinancia.tasas'),
        #),
        migrations.AlterField(
            model_name='financiacion',
            name='numero_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appfinancia.clientes'),
        ),
        #migrations.AlterField(
        #    model_name='prestamos',
        #    name='tipo_tasa',
        #    field=models.ForeignKey(blank=True, db_column='tipo_tasa', null=True, on_delete=django.db.models.deletion.PROTECT, to='appfinancia.tasas'),
        #),
    ]
