# Generated by Django 5.2.7 on 2026-01-14 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0107_remove_desembolsos_aseguradora_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desembolsos',
            name='aseguradora_id',
            field=models.ForeignKey(blank=True, db_column='aseguradora_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='appfinancia.aseguradoras'),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='asesor_id',
            field=models.ForeignKey(blank=True, db_column='asesor_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='appfinancia.asesores'),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='tipo_tasa',
            field=models.ForeignKey(blank=True, db_column='tipo_tasa', help_text="Tipo de tasa (ej. 'CON SEGURO').", null=True, on_delete=django.db.models.deletion.PROTECT, to='appfinancia.tasas'),
        ),
        migrations.AlterField(
            model_name='desembolsos',
            name='vendedor_id',
            field=models.ForeignKey(blank=True, db_column='vendedor_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='appfinancia.vendedores'),
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='aseguradora_id',
            field=models.ForeignKey(blank=True, db_column='aseguradora_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='appfinancia.aseguradoras'),
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='asesor_id',
            field=models.ForeignKey(blank=True, db_column='asesor_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='appfinancia.asesores'),
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='tipo_tasa',
            field=models.ForeignKey(blank=True, db_column='tipo_tasa', null=True, on_delete=django.db.models.deletion.PROTECT, to='appfinancia.tasas'),
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='vendedor_id',
            field=models.ForeignKey(blank=True, db_column='vendedor_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='appfinancia.vendedores'),
        ),
    ]
