# Generated by Django 5.2.7 on 2026-01-15 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0108_alter_desembolsos_aseguradora_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desembolsos',
            old_name='asesor_id',
            new_name='asesor',
        ),
        migrations.AddField(
            model_name='financiacion',
            name='adjunta_archivo_a',
            field=models.FileField(blank=True, null=True, upload_to='financiacion/archivo_a/'),
        ),
        migrations.AddField(
            model_name='financiacion',
            name='adjunta_archivo_b',
            field=models.FileField(blank=True, null=True, upload_to='financiacion/archivo_b/'),
        ),
        migrations.AddField(
            model_name='financiacion',
            name='adjunta_archivo_c',
            field=models.FileField(blank=True, null=True, upload_to='financiacion/archivo_c/'),
        ),
        migrations.AddField(
            model_name='financiacion',
            name='desembolso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financiaciones', to='appfinancia.desembolsos'),
        ),
    ]
