# Generated by Django 5.2.7 on 2026-01-19 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinancia', '0109_rename_asesor_id_desembolsos_asesor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fechas_sistema',
            options={'verbose_name': 'Parámetros Sistema', 'verbose_name_plural': 'Parámetros Sistema'},
        ),
        migrations.AlterModelOptions(
            name='financiacion',
            options={'verbose_name': 'Financiación', 'verbose_name_plural': 'Financiación'},
        ),
        migrations.AlterModelOptions(
            name='pagospararegularizar',
            options={'verbose_name': 'Pagos: 2.Gestión de pagos', 'verbose_name_plural': 'Pagos: 2.Gestión de pagos'},
        ),
       
        migrations.AddField(
            model_name='fechas_sistema',
            name='ambiente_sistema',
            field=models.CharField(choices=[('PRODUCCION', 'Producción'), ('CAPACITACION', 'Capacitación'), ('PRUEBAS', 'Pruebas')], default='PRUEBAS', help_text='Entorno del sistema: Producción, Capacitación, Pruebas', max_length=12),
        ),
        migrations.AddField(
            model_name='fechas_sistema',
            name='email_entrante',
            field=models.CharField(blank=True, help_text='Cuenta de correo para solicitudes de Financiación', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fechas_sistema',
            name='email_saliente',
            field=models.CharField(blank=True, help_text='Lista de correos para copias de salida', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='financiacion',
            name='num_pago_cuota_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financiaciones', to='appfinancia.inbox_pagosdetalle'),
        ),
        migrations.AddField(
            model_name='inbox_pagosdetalle',
            name='cuota_inicial',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2, null=True),
        ),
        
        migrations.AlterField(
            model_name='fechas_sistema',
            name='cambiado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fechas_sistema',
            name='fecha_proceso_actual',
            field=models.DateField(verbose_name='Fecha Proceso Actual'),
        ),
        migrations.AlterField(
            model_name='fechas_sistema',
            name='fecha_proceso_anterior',
            field=models.DateField(verbose_name='Fecha Proceso Anterior'),
        ),
        migrations.AlterField(
            model_name='fechas_sistema',
            name='fecha_proximo_proceso',
            field=models.DateField(verbose_name='Fecha Próximo Proceso'),
        ),
    ]
