"""
Django settings for CoreFinancia project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ==============================================================================
# SECURITY WARNING: keep the secret key used in production secret!
# ==============================================================================
SECRET_KEY = 'django-insecure-kt2pe_%dl1&o0dluf*ag0k)9c&^nqdpc%u3)rw)ua7u19(3@0a'


# ==============================================================================
# DEBUG & HOSTS — development only; change for production
# ==============================================================================

DEBUG = True


# ✅ Allow local + remote dev access (adjust in production!)
ALLOWED_HOSTS = ['72.60.172.191', 'localhost', '127.0.0.1']

#incluido 2025/12/23
# ==============================================================================
# --- Internacionalización y formato numérico (coma miles, punto decimales) ---
# ==============================================================================
LANGUAGE_CODE = 'es-co'
TIME_ZONE = 'America/Bogota'
USE_I18N = True
USE_TZ = True
# 🔴 CLAVE: desactivar localización automática
USE_L10N = False
USE_THOUSAND_SEPARATOR = True
THOUSAND_SEPARATOR = ','
DECIMAL_SEPARATOR = '.'
NUMBER_GROUPING = 3



# --- Archivos estáticos (requerido para el JS de formato) ---
#import os
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'appfinancia', 'static'),
]
# STATIC_ROOT = BASE_DIR / 'staticfiles'  # descomenta en producción

# ==============================================================================
# Application definition
# ==============================================================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',  # ← required for number formatting (e.g., intcomma)
    'smart_selects',
    'appfinancia',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'appfinancia.middleware.FechaSistemaMiddleware', #actualizar fechas_del sistema
]

ROOT_URLCONF = 'CoreFinancia.urls'

# ==============================================================================
# Templates
# ==============================================================================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'appfinancia', 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                # 🔹 CoreFinancia – Fecha de Proceso del Sistema
                'appfinancia.context_processors.fecha_sistema',
            ],
        },
    },
]

WSGI_APPLICATION = 'CoreFinancia.wsgi.application'


# ==============================================================================
# Database (PostgreSQL)
# ==============================================================================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'corefinancia_db',
        'USER': 'corefinancia_user',
        'PASSWORD': 'tu_contraseña_segura',
        'HOST': 'localhost',
        'PORT': '',
    }
}

# ==============================================================================
# Password validation
# ==============================================================================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ==============================================================================
# Default primary key field type
# ==============================================================================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==============================================================================
# Authentication & Login/Logout redirects
# ==============================================================================

#Para el login 2025.10.28
LOGIN_URL = '/admin/login/'   #2025-12-05
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'


# ==============================================================================
# Optional: Email (for ADMINS/MANAGERS error reporting)
# ==============================================================================
# SERVER_EMAIL = 'root@localhost'
# ADMINS = [("Tu Nombre", "tu@email.com")]
# MANAGERS = ADMINS


# ==============================================================================
# Control de cierre de sesión. 2025/11/24
# ==============================================================================

'''
# --- Sesión efímera: se destruye al cerrar el navegador ---
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # ← Clave principal

# Opcional: tiempo máximo de inactividad (ej: 30 minutos)
SESSION_COOKIE_AGE = 1800  # 30 minutos en segundos

# Asegurar que la cookie de sesión *no* sea persistente
SESSION_SAVE_EVERY_REQUEST = True  # renovar sesión en cada request (opcional, mejora UX)

# --- Seguridad adicional ---
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = True  # Solo si usas HTTPS en producción (¡requerido!)
SESSION_COOKIE_SAMESITE = 'Lax'  # o 'Strict' si no usas iframes
'''

#CONFIGURACIÓN PARA AMBIENTE DE DESARROLLO CON HTTP: 2025/11/24 pam

# Sesión efímera (se cierra al cerrar navegador)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 7200  # 7200 segundo de inactividad
SESSION_SAVE_EVERY_REQUEST = True

# 🔐 Solo activa SECURE si usas HTTPS
SESSION_COOKIE_SECURE = False   # ← Cambiado a False para HTTP 2025/11/24 pam
CSRF_COOKIE_SECURE = False      # ← Cambiado a False para HTTP 2025/11/24 pam
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True


# --- Autenticación Bakends --- 2025/11/24 pam
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

#incluido para leer los archivos adjuntos a los correos de Financiación. 2025/12/29
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
#-------------------------------------------

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# ===== IMAP (ENTRANTES) =====
IMAP_HOST = "imap.gmail.com"
IMAP_USER = "financia.seguros.pruebas@gmail.com"
IMAP_PASSWORD = "vbxstaiyahvelaxw"

# ===== SMTP (SALIENTES) =====
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = "financia.seguros.pruebas@gmail.com"
EMAIL_HOST_PASSWORD = "vbxstaiyahvelaxw"
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
# ===== FIN SMTP (SALIENTES) =====






